// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.tl.handshake.proto

package mtproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// /////////////////////////////////////////////////////////////////////////////
// Set_client_DH_params_answer <--
//  + TL_dh_gen_ok
//  + TL_dh_gen_retry
//  + TL_dh_gen_fail
//
type SetClient_DHParamsAnswer_Data struct {
	Nonce                []byte   `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce          []byte   `protobuf:"bytes,2,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	NewNonceHash1        []byte   `protobuf:"bytes,3,opt,name=new_nonce_hash1,json=newNonceHash1,proto3" json:"new_nonce_hash1,omitempty"`
	NewNonceHash2        []byte   `protobuf:"bytes,4,opt,name=new_nonce_hash2,json=newNonceHash2,proto3" json:"new_nonce_hash2,omitempty"`
	NewNonceHash3        []byte   `protobuf:"bytes,5,opt,name=new_nonce_hash3,json=newNonceHash3,proto3" json:"new_nonce_hash3,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetClient_DHParamsAnswer_Data) Reset()         { *m = SetClient_DHParamsAnswer_Data{} }
func (m *SetClient_DHParamsAnswer_Data) String() string { return proto.CompactTextString(m) }
func (*SetClient_DHParamsAnswer_Data) ProtoMessage()    {}
func (*SetClient_DHParamsAnswer_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{0}
}
func (m *SetClient_DHParamsAnswer_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetClient_DHParamsAnswer_Data.Unmarshal(m, b)
}
func (m *SetClient_DHParamsAnswer_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetClient_DHParamsAnswer_Data.Marshal(b, m, deterministic)
}
func (dst *SetClient_DHParamsAnswer_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetClient_DHParamsAnswer_Data.Merge(dst, src)
}
func (m *SetClient_DHParamsAnswer_Data) XXX_Size() int {
	return xxx_messageInfo_SetClient_DHParamsAnswer_Data.Size(m)
}
func (m *SetClient_DHParamsAnswer_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_SetClient_DHParamsAnswer_Data.DiscardUnknown(m)
}

var xxx_messageInfo_SetClient_DHParamsAnswer_Data proto.InternalMessageInfo

func (m *SetClient_DHParamsAnswer_Data) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *SetClient_DHParamsAnswer_Data) GetServerNonce() []byte {
	if m != nil {
		return m.ServerNonce
	}
	return nil
}

func (m *SetClient_DHParamsAnswer_Data) GetNewNonceHash1() []byte {
	if m != nil {
		return m.NewNonceHash1
	}
	return nil
}

func (m *SetClient_DHParamsAnswer_Data) GetNewNonceHash2() []byte {
	if m != nil {
		return m.NewNonceHash2
	}
	return nil
}

func (m *SetClient_DHParamsAnswer_Data) GetNewNonceHash3() []byte {
	if m != nil {
		return m.NewNonceHash3
	}
	return nil
}

type SetClient_DHParamsAnswer struct {
	Constructor          TLConstructor                  `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2                *SetClient_DHParamsAnswer_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *SetClient_DHParamsAnswer) Reset()         { *m = SetClient_DHParamsAnswer{} }
func (m *SetClient_DHParamsAnswer) String() string { return proto.CompactTextString(m) }
func (*SetClient_DHParamsAnswer) ProtoMessage()    {}
func (*SetClient_DHParamsAnswer) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{1}
}
func (m *SetClient_DHParamsAnswer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetClient_DHParamsAnswer.Unmarshal(m, b)
}
func (m *SetClient_DHParamsAnswer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetClient_DHParamsAnswer.Marshal(b, m, deterministic)
}
func (dst *SetClient_DHParamsAnswer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetClient_DHParamsAnswer.Merge(dst, src)
}
func (m *SetClient_DHParamsAnswer) XXX_Size() int {
	return xxx_messageInfo_SetClient_DHParamsAnswer.Size(m)
}
func (m *SetClient_DHParamsAnswer) XXX_DiscardUnknown() {
	xxx_messageInfo_SetClient_DHParamsAnswer.DiscardUnknown(m)
}

var xxx_messageInfo_SetClient_DHParamsAnswer proto.InternalMessageInfo

func (m *SetClient_DHParamsAnswer) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *SetClient_DHParamsAnswer) GetData2() *SetClient_DHParamsAnswer_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// dh_gen_ok#3bcbf734 nonce:int128 server_nonce:int128 new_nonce_hash1:int128 = Set_client_DH_params_answer;
type TLDhGenOk struct {
	Data2                *SetClient_DHParamsAnswer_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *TLDhGenOk) Reset()         { *m = TLDhGenOk{} }
func (m *TLDhGenOk) String() string { return proto.CompactTextString(m) }
func (*TLDhGenOk) ProtoMessage()    {}
func (*TLDhGenOk) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{2}
}
func (m *TLDhGenOk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLDhGenOk.Unmarshal(m, b)
}
func (m *TLDhGenOk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLDhGenOk.Marshal(b, m, deterministic)
}
func (dst *TLDhGenOk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLDhGenOk.Merge(dst, src)
}
func (m *TLDhGenOk) XXX_Size() int {
	return xxx_messageInfo_TLDhGenOk.Size(m)
}
func (m *TLDhGenOk) XXX_DiscardUnknown() {
	xxx_messageInfo_TLDhGenOk.DiscardUnknown(m)
}

var xxx_messageInfo_TLDhGenOk proto.InternalMessageInfo

func (m *TLDhGenOk) GetData2() *SetClient_DHParamsAnswer_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// dh_gen_retry#46dc1fb9 nonce:int128 server_nonce:int128 new_nonce_hash2:int128 = Set_client_DH_params_answer;
type TLDhGenRetry struct {
	Data2                *SetClient_DHParamsAnswer_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *TLDhGenRetry) Reset()         { *m = TLDhGenRetry{} }
func (m *TLDhGenRetry) String() string { return proto.CompactTextString(m) }
func (*TLDhGenRetry) ProtoMessage()    {}
func (*TLDhGenRetry) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{3}
}
func (m *TLDhGenRetry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLDhGenRetry.Unmarshal(m, b)
}
func (m *TLDhGenRetry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLDhGenRetry.Marshal(b, m, deterministic)
}
func (dst *TLDhGenRetry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLDhGenRetry.Merge(dst, src)
}
func (m *TLDhGenRetry) XXX_Size() int {
	return xxx_messageInfo_TLDhGenRetry.Size(m)
}
func (m *TLDhGenRetry) XXX_DiscardUnknown() {
	xxx_messageInfo_TLDhGenRetry.DiscardUnknown(m)
}

var xxx_messageInfo_TLDhGenRetry proto.InternalMessageInfo

func (m *TLDhGenRetry) GetData2() *SetClient_DHParamsAnswer_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// dh_gen_fail#a69dae02 nonce:int128 server_nonce:int128 new_nonce_hash3:int128 = Set_client_DH_params_answer;
type TLDhGenFail struct {
	Data2                *SetClient_DHParamsAnswer_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *TLDhGenFail) Reset()         { *m = TLDhGenFail{} }
func (m *TLDhGenFail) String() string { return proto.CompactTextString(m) }
func (*TLDhGenFail) ProtoMessage()    {}
func (*TLDhGenFail) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{4}
}
func (m *TLDhGenFail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLDhGenFail.Unmarshal(m, b)
}
func (m *TLDhGenFail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLDhGenFail.Marshal(b, m, deterministic)
}
func (dst *TLDhGenFail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLDhGenFail.Merge(dst, src)
}
func (m *TLDhGenFail) XXX_Size() int {
	return xxx_messageInfo_TLDhGenFail.Size(m)
}
func (m *TLDhGenFail) XXX_DiscardUnknown() {
	xxx_messageInfo_TLDhGenFail.DiscardUnknown(m)
}

var xxx_messageInfo_TLDhGenFail proto.InternalMessageInfo

func (m *TLDhGenFail) GetData2() *SetClient_DHParamsAnswer_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// DestroyAuthKeyRes <--
//  + TL_destroy_auth_key_ok
//  + TL_destroy_auth_key_none
//  + TL_destroy_auth_key_fail
//
type DestroyAuthKeyRes_Data struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DestroyAuthKeyRes_Data) Reset()         { *m = DestroyAuthKeyRes_Data{} }
func (m *DestroyAuthKeyRes_Data) String() string { return proto.CompactTextString(m) }
func (*DestroyAuthKeyRes_Data) ProtoMessage()    {}
func (*DestroyAuthKeyRes_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{5}
}
func (m *DestroyAuthKeyRes_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroyAuthKeyRes_Data.Unmarshal(m, b)
}
func (m *DestroyAuthKeyRes_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroyAuthKeyRes_Data.Marshal(b, m, deterministic)
}
func (dst *DestroyAuthKeyRes_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroyAuthKeyRes_Data.Merge(dst, src)
}
func (m *DestroyAuthKeyRes_Data) XXX_Size() int {
	return xxx_messageInfo_DestroyAuthKeyRes_Data.Size(m)
}
func (m *DestroyAuthKeyRes_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroyAuthKeyRes_Data.DiscardUnknown(m)
}

var xxx_messageInfo_DestroyAuthKeyRes_Data proto.InternalMessageInfo

type DestroyAuthKeyRes struct {
	Constructor          TLConstructor           `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2                *DestroyAuthKeyRes_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *DestroyAuthKeyRes) Reset()         { *m = DestroyAuthKeyRes{} }
func (m *DestroyAuthKeyRes) String() string { return proto.CompactTextString(m) }
func (*DestroyAuthKeyRes) ProtoMessage()    {}
func (*DestroyAuthKeyRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{6}
}
func (m *DestroyAuthKeyRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroyAuthKeyRes.Unmarshal(m, b)
}
func (m *DestroyAuthKeyRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroyAuthKeyRes.Marshal(b, m, deterministic)
}
func (dst *DestroyAuthKeyRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroyAuthKeyRes.Merge(dst, src)
}
func (m *DestroyAuthKeyRes) XXX_Size() int {
	return xxx_messageInfo_DestroyAuthKeyRes.Size(m)
}
func (m *DestroyAuthKeyRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroyAuthKeyRes.DiscardUnknown(m)
}

var xxx_messageInfo_DestroyAuthKeyRes proto.InternalMessageInfo

func (m *DestroyAuthKeyRes) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *DestroyAuthKeyRes) GetData2() *DestroyAuthKeyRes_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// destroy_auth_key_ok#f660e1d4 = DestroyAuthKeyRes;
type TLDestroyAuthKeyOk struct {
	Data2                *DestroyAuthKeyRes_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TLDestroyAuthKeyOk) Reset()         { *m = TLDestroyAuthKeyOk{} }
func (m *TLDestroyAuthKeyOk) String() string { return proto.CompactTextString(m) }
func (*TLDestroyAuthKeyOk) ProtoMessage()    {}
func (*TLDestroyAuthKeyOk) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{7}
}
func (m *TLDestroyAuthKeyOk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLDestroyAuthKeyOk.Unmarshal(m, b)
}
func (m *TLDestroyAuthKeyOk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLDestroyAuthKeyOk.Marshal(b, m, deterministic)
}
func (dst *TLDestroyAuthKeyOk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLDestroyAuthKeyOk.Merge(dst, src)
}
func (m *TLDestroyAuthKeyOk) XXX_Size() int {
	return xxx_messageInfo_TLDestroyAuthKeyOk.Size(m)
}
func (m *TLDestroyAuthKeyOk) XXX_DiscardUnknown() {
	xxx_messageInfo_TLDestroyAuthKeyOk.DiscardUnknown(m)
}

var xxx_messageInfo_TLDestroyAuthKeyOk proto.InternalMessageInfo

func (m *TLDestroyAuthKeyOk) GetData2() *DestroyAuthKeyRes_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// destroy_auth_key_none#0a9f2259 = DestroyAuthKeyRes;
type TLDestroyAuthKeyNone struct {
	Data2                *DestroyAuthKeyRes_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TLDestroyAuthKeyNone) Reset()         { *m = TLDestroyAuthKeyNone{} }
func (m *TLDestroyAuthKeyNone) String() string { return proto.CompactTextString(m) }
func (*TLDestroyAuthKeyNone) ProtoMessage()    {}
func (*TLDestroyAuthKeyNone) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{8}
}
func (m *TLDestroyAuthKeyNone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLDestroyAuthKeyNone.Unmarshal(m, b)
}
func (m *TLDestroyAuthKeyNone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLDestroyAuthKeyNone.Marshal(b, m, deterministic)
}
func (dst *TLDestroyAuthKeyNone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLDestroyAuthKeyNone.Merge(dst, src)
}
func (m *TLDestroyAuthKeyNone) XXX_Size() int {
	return xxx_messageInfo_TLDestroyAuthKeyNone.Size(m)
}
func (m *TLDestroyAuthKeyNone) XXX_DiscardUnknown() {
	xxx_messageInfo_TLDestroyAuthKeyNone.DiscardUnknown(m)
}

var xxx_messageInfo_TLDestroyAuthKeyNone proto.InternalMessageInfo

func (m *TLDestroyAuthKeyNone) GetData2() *DestroyAuthKeyRes_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// destroy_auth_key_fail#ea109b13 = DestroyAuthKeyRes;
type TLDestroyAuthKeyFail struct {
	Data2                *DestroyAuthKeyRes_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TLDestroyAuthKeyFail) Reset()         { *m = TLDestroyAuthKeyFail{} }
func (m *TLDestroyAuthKeyFail) String() string { return proto.CompactTextString(m) }
func (*TLDestroyAuthKeyFail) ProtoMessage()    {}
func (*TLDestroyAuthKeyFail) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{9}
}
func (m *TLDestroyAuthKeyFail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLDestroyAuthKeyFail.Unmarshal(m, b)
}
func (m *TLDestroyAuthKeyFail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLDestroyAuthKeyFail.Marshal(b, m, deterministic)
}
func (dst *TLDestroyAuthKeyFail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLDestroyAuthKeyFail.Merge(dst, src)
}
func (m *TLDestroyAuthKeyFail) XXX_Size() int {
	return xxx_messageInfo_TLDestroyAuthKeyFail.Size(m)
}
func (m *TLDestroyAuthKeyFail) XXX_DiscardUnknown() {
	xxx_messageInfo_TLDestroyAuthKeyFail.DiscardUnknown(m)
}

var xxx_messageInfo_TLDestroyAuthKeyFail proto.InternalMessageInfo

func (m *TLDestroyAuthKeyFail) GetData2() *DestroyAuthKeyRes_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// ResPQ <--
//  + TL_resPQ
//
type ResPQ_Data struct {
	Nonce                       []byte   `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce                 []byte   `protobuf:"bytes,2,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	Pq                          string   `protobuf:"bytes,3,opt,name=pq,proto3" json:"pq,omitempty"`
	ServerPublicKeyFingerprints []int64  `protobuf:"varint,4,rep,packed,name=server_public_key_fingerprints,json=serverPublicKeyFingerprints,proto3" json:"server_public_key_fingerprints,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *ResPQ_Data) Reset()         { *m = ResPQ_Data{} }
func (m *ResPQ_Data) String() string { return proto.CompactTextString(m) }
func (*ResPQ_Data) ProtoMessage()    {}
func (*ResPQ_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{10}
}
func (m *ResPQ_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResPQ_Data.Unmarshal(m, b)
}
func (m *ResPQ_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResPQ_Data.Marshal(b, m, deterministic)
}
func (dst *ResPQ_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResPQ_Data.Merge(dst, src)
}
func (m *ResPQ_Data) XXX_Size() int {
	return xxx_messageInfo_ResPQ_Data.Size(m)
}
func (m *ResPQ_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_ResPQ_Data.DiscardUnknown(m)
}

var xxx_messageInfo_ResPQ_Data proto.InternalMessageInfo

func (m *ResPQ_Data) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *ResPQ_Data) GetServerNonce() []byte {
	if m != nil {
		return m.ServerNonce
	}
	return nil
}

func (m *ResPQ_Data) GetPq() string {
	if m != nil {
		return m.Pq
	}
	return ""
}

func (m *ResPQ_Data) GetServerPublicKeyFingerprints() []int64 {
	if m != nil {
		return m.ServerPublicKeyFingerprints
	}
	return nil
}

type ResPQ struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2                *ResPQ_Data   `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ResPQ) Reset()         { *m = ResPQ{} }
func (m *ResPQ) String() string { return proto.CompactTextString(m) }
func (*ResPQ) ProtoMessage()    {}
func (*ResPQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{11}
}
func (m *ResPQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResPQ.Unmarshal(m, b)
}
func (m *ResPQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResPQ.Marshal(b, m, deterministic)
}
func (dst *ResPQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResPQ.Merge(dst, src)
}
func (m *ResPQ) XXX_Size() int {
	return xxx_messageInfo_ResPQ.Size(m)
}
func (m *ResPQ) XXX_DiscardUnknown() {
	xxx_messageInfo_ResPQ.DiscardUnknown(m)
}

var xxx_messageInfo_ResPQ proto.InternalMessageInfo

func (m *ResPQ) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *ResPQ) GetData2() *ResPQ_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// resPQ#05162463 nonce:int128 server_nonce:int128 pq:string server_public_key_fingerprints:Vector<long> = ResPQ;
type TLResPQ struct {
	Data2                *ResPQ_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TLResPQ) Reset()         { *m = TLResPQ{} }
func (m *TLResPQ) String() string { return proto.CompactTextString(m) }
func (*TLResPQ) ProtoMessage()    {}
func (*TLResPQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{12}
}
func (m *TLResPQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLResPQ.Unmarshal(m, b)
}
func (m *TLResPQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLResPQ.Marshal(b, m, deterministic)
}
func (dst *TLResPQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLResPQ.Merge(dst, src)
}
func (m *TLResPQ) XXX_Size() int {
	return xxx_messageInfo_TLResPQ.Size(m)
}
func (m *TLResPQ) XXX_DiscardUnknown() {
	xxx_messageInfo_TLResPQ.DiscardUnknown(m)
}

var xxx_messageInfo_TLResPQ proto.InternalMessageInfo

func (m *TLResPQ) GetData2() *ResPQ_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// P_Q_inner_data <--
//  + TL_p_q_inner_data
//  + TL_p_q_inner_data_dc
//  + TL_p_q_inner_data_temp
//  + TL_p_q_inner_data_temp_dc
//
type P_QInnerData_Data struct {
	Pq                   string   `protobuf:"bytes,1,opt,name=pq,proto3" json:"pq,omitempty"`
	P                    string   `protobuf:"bytes,2,opt,name=p,proto3" json:"p,omitempty"`
	Q                    string   `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"`
	Nonce                []byte   `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce          []byte   `protobuf:"bytes,5,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	NewNonce             []byte   `protobuf:"bytes,6,opt,name=new_nonce,json=newNonce,proto3" json:"new_nonce,omitempty"`
	Dc                   int32    `protobuf:"varint,7,opt,name=dc,proto3" json:"dc,omitempty"`
	ExpiresIn            int32    `protobuf:"varint,8,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *P_QInnerData_Data) Reset()         { *m = P_QInnerData_Data{} }
func (m *P_QInnerData_Data) String() string { return proto.CompactTextString(m) }
func (*P_QInnerData_Data) ProtoMessage()    {}
func (*P_QInnerData_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{13}
}
func (m *P_QInnerData_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P_QInnerData_Data.Unmarshal(m, b)
}
func (m *P_QInnerData_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P_QInnerData_Data.Marshal(b, m, deterministic)
}
func (dst *P_QInnerData_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P_QInnerData_Data.Merge(dst, src)
}
func (m *P_QInnerData_Data) XXX_Size() int {
	return xxx_messageInfo_P_QInnerData_Data.Size(m)
}
func (m *P_QInnerData_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_P_QInnerData_Data.DiscardUnknown(m)
}

var xxx_messageInfo_P_QInnerData_Data proto.InternalMessageInfo

func (m *P_QInnerData_Data) GetPq() string {
	if m != nil {
		return m.Pq
	}
	return ""
}

func (m *P_QInnerData_Data) GetP() string {
	if m != nil {
		return m.P
	}
	return ""
}

func (m *P_QInnerData_Data) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *P_QInnerData_Data) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *P_QInnerData_Data) GetServerNonce() []byte {
	if m != nil {
		return m.ServerNonce
	}
	return nil
}

func (m *P_QInnerData_Data) GetNewNonce() []byte {
	if m != nil {
		return m.NewNonce
	}
	return nil
}

func (m *P_QInnerData_Data) GetDc() int32 {
	if m != nil {
		return m.Dc
	}
	return 0
}

func (m *P_QInnerData_Data) GetExpiresIn() int32 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

type P_QInnerData struct {
	Constructor          TLConstructor      `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2                *P_QInnerData_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *P_QInnerData) Reset()         { *m = P_QInnerData{} }
func (m *P_QInnerData) String() string { return proto.CompactTextString(m) }
func (*P_QInnerData) ProtoMessage()    {}
func (*P_QInnerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{14}
}
func (m *P_QInnerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P_QInnerData.Unmarshal(m, b)
}
func (m *P_QInnerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P_QInnerData.Marshal(b, m, deterministic)
}
func (dst *P_QInnerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P_QInnerData.Merge(dst, src)
}
func (m *P_QInnerData) XXX_Size() int {
	return xxx_messageInfo_P_QInnerData.Size(m)
}
func (m *P_QInnerData) XXX_DiscardUnknown() {
	xxx_messageInfo_P_QInnerData.DiscardUnknown(m)
}

var xxx_messageInfo_P_QInnerData proto.InternalMessageInfo

func (m *P_QInnerData) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *P_QInnerData) GetData2() *P_QInnerData_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// p_q_inner_data#83c95aec pq:string p:string q:string nonce:int128 server_nonce:int128 new_nonce:int256 = P_Q_inner_data;
type TLPQInnerData struct {
	Data2                *P_QInnerData_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TLPQInnerData) Reset()         { *m = TLPQInnerData{} }
func (m *TLPQInnerData) String() string { return proto.CompactTextString(m) }
func (*TLPQInnerData) ProtoMessage()    {}
func (*TLPQInnerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{15}
}
func (m *TLPQInnerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLPQInnerData.Unmarshal(m, b)
}
func (m *TLPQInnerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLPQInnerData.Marshal(b, m, deterministic)
}
func (dst *TLPQInnerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLPQInnerData.Merge(dst, src)
}
func (m *TLPQInnerData) XXX_Size() int {
	return xxx_messageInfo_TLPQInnerData.Size(m)
}
func (m *TLPQInnerData) XXX_DiscardUnknown() {
	xxx_messageInfo_TLPQInnerData.DiscardUnknown(m)
}

var xxx_messageInfo_TLPQInnerData proto.InternalMessageInfo

func (m *TLPQInnerData) GetData2() *P_QInnerData_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// p_q_inner_data_dc#a9f55f95 pq:string p:string q:string nonce:int128 server_nonce:int128 new_nonce:int256 dc:int = P_Q_inner_data;
type TLPQInnerDataDc struct {
	Data2                *P_QInnerData_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TLPQInnerDataDc) Reset()         { *m = TLPQInnerDataDc{} }
func (m *TLPQInnerDataDc) String() string { return proto.CompactTextString(m) }
func (*TLPQInnerDataDc) ProtoMessage()    {}
func (*TLPQInnerDataDc) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{16}
}
func (m *TLPQInnerDataDc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLPQInnerDataDc.Unmarshal(m, b)
}
func (m *TLPQInnerDataDc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLPQInnerDataDc.Marshal(b, m, deterministic)
}
func (dst *TLPQInnerDataDc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLPQInnerDataDc.Merge(dst, src)
}
func (m *TLPQInnerDataDc) XXX_Size() int {
	return xxx_messageInfo_TLPQInnerDataDc.Size(m)
}
func (m *TLPQInnerDataDc) XXX_DiscardUnknown() {
	xxx_messageInfo_TLPQInnerDataDc.DiscardUnknown(m)
}

var xxx_messageInfo_TLPQInnerDataDc proto.InternalMessageInfo

func (m *TLPQInnerDataDc) GetData2() *P_QInnerData_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// p_q_inner_data_temp#3c6a84d4 pq:string p:string q:string nonce:int128 server_nonce:int128 new_nonce:int256 expires_in:int = P_Q_inner_data;
type TLPQInnerDataTemp struct {
	Data2                *P_QInnerData_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TLPQInnerDataTemp) Reset()         { *m = TLPQInnerDataTemp{} }
func (m *TLPQInnerDataTemp) String() string { return proto.CompactTextString(m) }
func (*TLPQInnerDataTemp) ProtoMessage()    {}
func (*TLPQInnerDataTemp) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{17}
}
func (m *TLPQInnerDataTemp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLPQInnerDataTemp.Unmarshal(m, b)
}
func (m *TLPQInnerDataTemp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLPQInnerDataTemp.Marshal(b, m, deterministic)
}
func (dst *TLPQInnerDataTemp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLPQInnerDataTemp.Merge(dst, src)
}
func (m *TLPQInnerDataTemp) XXX_Size() int {
	return xxx_messageInfo_TLPQInnerDataTemp.Size(m)
}
func (m *TLPQInnerDataTemp) XXX_DiscardUnknown() {
	xxx_messageInfo_TLPQInnerDataTemp.DiscardUnknown(m)
}

var xxx_messageInfo_TLPQInnerDataTemp proto.InternalMessageInfo

func (m *TLPQInnerDataTemp) GetData2() *P_QInnerData_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// p_q_inner_data_temp_dc#56fddf88 pq:string p:string q:string nonce:int128 server_nonce:int128 new_nonce:int256 dc:int expires_in:int = P_Q_inner_data;
type TLPQInnerDataTempDc struct {
	Data2                *P_QInnerData_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TLPQInnerDataTempDc) Reset()         { *m = TLPQInnerDataTempDc{} }
func (m *TLPQInnerDataTempDc) String() string { return proto.CompactTextString(m) }
func (*TLPQInnerDataTempDc) ProtoMessage()    {}
func (*TLPQInnerDataTempDc) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{18}
}
func (m *TLPQInnerDataTempDc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLPQInnerDataTempDc.Unmarshal(m, b)
}
func (m *TLPQInnerDataTempDc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLPQInnerDataTempDc.Marshal(b, m, deterministic)
}
func (dst *TLPQInnerDataTempDc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLPQInnerDataTempDc.Merge(dst, src)
}
func (m *TLPQInnerDataTempDc) XXX_Size() int {
	return xxx_messageInfo_TLPQInnerDataTempDc.Size(m)
}
func (m *TLPQInnerDataTempDc) XXX_DiscardUnknown() {
	xxx_messageInfo_TLPQInnerDataTempDc.DiscardUnknown(m)
}

var xxx_messageInfo_TLPQInnerDataTempDc proto.InternalMessageInfo

func (m *TLPQInnerDataTempDc) GetData2() *P_QInnerData_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// Server_DH_Params <--
//  + TL_server_DH_params_fail
//  + TL_server_DH_params_ok
//
type Server_DH_Params_Data struct {
	Nonce                []byte   `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce          []byte   `protobuf:"bytes,2,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	NewNonceHash         []byte   `protobuf:"bytes,3,opt,name=new_nonce_hash,json=newNonceHash,proto3" json:"new_nonce_hash,omitempty"`
	EncryptedAnswer      string   `protobuf:"bytes,4,opt,name=encrypted_answer,json=encryptedAnswer,proto3" json:"encrypted_answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Server_DH_Params_Data) Reset()         { *m = Server_DH_Params_Data{} }
func (m *Server_DH_Params_Data) String() string { return proto.CompactTextString(m) }
func (*Server_DH_Params_Data) ProtoMessage()    {}
func (*Server_DH_Params_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{19}
}
func (m *Server_DH_Params_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server_DH_Params_Data.Unmarshal(m, b)
}
func (m *Server_DH_Params_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server_DH_Params_Data.Marshal(b, m, deterministic)
}
func (dst *Server_DH_Params_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server_DH_Params_Data.Merge(dst, src)
}
func (m *Server_DH_Params_Data) XXX_Size() int {
	return xxx_messageInfo_Server_DH_Params_Data.Size(m)
}
func (m *Server_DH_Params_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Server_DH_Params_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Server_DH_Params_Data proto.InternalMessageInfo

func (m *Server_DH_Params_Data) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *Server_DH_Params_Data) GetServerNonce() []byte {
	if m != nil {
		return m.ServerNonce
	}
	return nil
}

func (m *Server_DH_Params_Data) GetNewNonceHash() []byte {
	if m != nil {
		return m.NewNonceHash
	}
	return nil
}

func (m *Server_DH_Params_Data) GetEncryptedAnswer() string {
	if m != nil {
		return m.EncryptedAnswer
	}
	return ""
}

type Server_DH_Params struct {
	Constructor          TLConstructor          `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2                *Server_DH_Params_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Server_DH_Params) Reset()         { *m = Server_DH_Params{} }
func (m *Server_DH_Params) String() string { return proto.CompactTextString(m) }
func (*Server_DH_Params) ProtoMessage()    {}
func (*Server_DH_Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{20}
}
func (m *Server_DH_Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server_DH_Params.Unmarshal(m, b)
}
func (m *Server_DH_Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server_DH_Params.Marshal(b, m, deterministic)
}
func (dst *Server_DH_Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server_DH_Params.Merge(dst, src)
}
func (m *Server_DH_Params) XXX_Size() int {
	return xxx_messageInfo_Server_DH_Params.Size(m)
}
func (m *Server_DH_Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Server_DH_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Server_DH_Params proto.InternalMessageInfo

func (m *Server_DH_Params) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *Server_DH_Params) GetData2() *Server_DH_Params_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// server_DH_params_fail#79cb045d nonce:int128 server_nonce:int128 new_nonce_hash:int128 = Server_DH_Params;
type TLServer_DHParamsFail struct {
	Data2                *Server_DH_Params_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TLServer_DHParamsFail) Reset()         { *m = TLServer_DHParamsFail{} }
func (m *TLServer_DHParamsFail) String() string { return proto.CompactTextString(m) }
func (*TLServer_DHParamsFail) ProtoMessage()    {}
func (*TLServer_DHParamsFail) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{21}
}
func (m *TLServer_DHParamsFail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLServer_DHParamsFail.Unmarshal(m, b)
}
func (m *TLServer_DHParamsFail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLServer_DHParamsFail.Marshal(b, m, deterministic)
}
func (dst *TLServer_DHParamsFail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLServer_DHParamsFail.Merge(dst, src)
}
func (m *TLServer_DHParamsFail) XXX_Size() int {
	return xxx_messageInfo_TLServer_DHParamsFail.Size(m)
}
func (m *TLServer_DHParamsFail) XXX_DiscardUnknown() {
	xxx_messageInfo_TLServer_DHParamsFail.DiscardUnknown(m)
}

var xxx_messageInfo_TLServer_DHParamsFail proto.InternalMessageInfo

func (m *TLServer_DHParamsFail) GetData2() *Server_DH_Params_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// server_DH_params_ok#d0e8075c nonce:int128 server_nonce:int128 encrypted_answer:string = Server_DH_Params;
type TLServer_DHParamsOk struct {
	Data2                *Server_DH_Params_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TLServer_DHParamsOk) Reset()         { *m = TLServer_DHParamsOk{} }
func (m *TLServer_DHParamsOk) String() string { return proto.CompactTextString(m) }
func (*TLServer_DHParamsOk) ProtoMessage()    {}
func (*TLServer_DHParamsOk) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{22}
}
func (m *TLServer_DHParamsOk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLServer_DHParamsOk.Unmarshal(m, b)
}
func (m *TLServer_DHParamsOk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLServer_DHParamsOk.Marshal(b, m, deterministic)
}
func (dst *TLServer_DHParamsOk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLServer_DHParamsOk.Merge(dst, src)
}
func (m *TLServer_DHParamsOk) XXX_Size() int {
	return xxx_messageInfo_TLServer_DHParamsOk.Size(m)
}
func (m *TLServer_DHParamsOk) XXX_DiscardUnknown() {
	xxx_messageInfo_TLServer_DHParamsOk.DiscardUnknown(m)
}

var xxx_messageInfo_TLServer_DHParamsOk proto.InternalMessageInfo

func (m *TLServer_DHParamsOk) GetData2() *Server_DH_Params_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// Server_DH_inner_data <--
//  + TL_server_DH_inner_data
//
type Server_DHInnerData_Data struct {
	Nonce                []byte   `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce          []byte   `protobuf:"bytes,2,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	G                    int32    `protobuf:"varint,3,opt,name=g,proto3" json:"g,omitempty"`
	DhPrime              string   `protobuf:"bytes,4,opt,name=dh_prime,json=dhPrime,proto3" json:"dh_prime,omitempty"`
	GA                   string   `protobuf:"bytes,5,opt,name=g_a,json=gA,proto3" json:"g_a,omitempty"`
	ServerTime           int32    `protobuf:"varint,6,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Server_DHInnerData_Data) Reset()         { *m = Server_DHInnerData_Data{} }
func (m *Server_DHInnerData_Data) String() string { return proto.CompactTextString(m) }
func (*Server_DHInnerData_Data) ProtoMessage()    {}
func (*Server_DHInnerData_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{23}
}
func (m *Server_DHInnerData_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server_DHInnerData_Data.Unmarshal(m, b)
}
func (m *Server_DHInnerData_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server_DHInnerData_Data.Marshal(b, m, deterministic)
}
func (dst *Server_DHInnerData_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server_DHInnerData_Data.Merge(dst, src)
}
func (m *Server_DHInnerData_Data) XXX_Size() int {
	return xxx_messageInfo_Server_DHInnerData_Data.Size(m)
}
func (m *Server_DHInnerData_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Server_DHInnerData_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Server_DHInnerData_Data proto.InternalMessageInfo

func (m *Server_DHInnerData_Data) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *Server_DHInnerData_Data) GetServerNonce() []byte {
	if m != nil {
		return m.ServerNonce
	}
	return nil
}

func (m *Server_DHInnerData_Data) GetG() int32 {
	if m != nil {
		return m.G
	}
	return 0
}

func (m *Server_DHInnerData_Data) GetDhPrime() string {
	if m != nil {
		return m.DhPrime
	}
	return ""
}

func (m *Server_DHInnerData_Data) GetGA() string {
	if m != nil {
		return m.GA
	}
	return ""
}

func (m *Server_DHInnerData_Data) GetServerTime() int32 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

type Server_DHInnerData struct {
	Constructor          TLConstructor            `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2                *Server_DHInnerData_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Server_DHInnerData) Reset()         { *m = Server_DHInnerData{} }
func (m *Server_DHInnerData) String() string { return proto.CompactTextString(m) }
func (*Server_DHInnerData) ProtoMessage()    {}
func (*Server_DHInnerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{24}
}
func (m *Server_DHInnerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server_DHInnerData.Unmarshal(m, b)
}
func (m *Server_DHInnerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server_DHInnerData.Marshal(b, m, deterministic)
}
func (dst *Server_DHInnerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server_DHInnerData.Merge(dst, src)
}
func (m *Server_DHInnerData) XXX_Size() int {
	return xxx_messageInfo_Server_DHInnerData.Size(m)
}
func (m *Server_DHInnerData) XXX_DiscardUnknown() {
	xxx_messageInfo_Server_DHInnerData.DiscardUnknown(m)
}

var xxx_messageInfo_Server_DHInnerData proto.InternalMessageInfo

func (m *Server_DHInnerData) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *Server_DHInnerData) GetData2() *Server_DHInnerData_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// server_DH_inner_data#b5890dba nonce:int128 server_nonce:int128 g:int dh_prime:string g_a:string server_time:int = Server_DH_inner_data;
type TLServer_DHInnerData struct {
	Data2                *Server_DHInnerData_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *TLServer_DHInnerData) Reset()         { *m = TLServer_DHInnerData{} }
func (m *TLServer_DHInnerData) String() string { return proto.CompactTextString(m) }
func (*TLServer_DHInnerData) ProtoMessage()    {}
func (*TLServer_DHInnerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{25}
}
func (m *TLServer_DHInnerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLServer_DHInnerData.Unmarshal(m, b)
}
func (m *TLServer_DHInnerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLServer_DHInnerData.Marshal(b, m, deterministic)
}
func (dst *TLServer_DHInnerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLServer_DHInnerData.Merge(dst, src)
}
func (m *TLServer_DHInnerData) XXX_Size() int {
	return xxx_messageInfo_TLServer_DHInnerData.Size(m)
}
func (m *TLServer_DHInnerData) XXX_DiscardUnknown() {
	xxx_messageInfo_TLServer_DHInnerData.DiscardUnknown(m)
}

var xxx_messageInfo_TLServer_DHInnerData proto.InternalMessageInfo

func (m *TLServer_DHInnerData) GetData2() *Server_DHInnerData_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// Client_DH_Inner_Data <--
//  + TL_client_DH_inner_data
//
type Client_DH_Inner_Data_Data struct {
	Nonce                []byte   `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce          []byte   `protobuf:"bytes,2,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	RetryId              int64    `protobuf:"varint,3,opt,name=retry_id,json=retryId,proto3" json:"retry_id,omitempty"`
	GB                   string   `protobuf:"bytes,4,opt,name=g_b,json=gB,proto3" json:"g_b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Client_DH_Inner_Data_Data) Reset()         { *m = Client_DH_Inner_Data_Data{} }
func (m *Client_DH_Inner_Data_Data) String() string { return proto.CompactTextString(m) }
func (*Client_DH_Inner_Data_Data) ProtoMessage()    {}
func (*Client_DH_Inner_Data_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{26}
}
func (m *Client_DH_Inner_Data_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client_DH_Inner_Data_Data.Unmarshal(m, b)
}
func (m *Client_DH_Inner_Data_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client_DH_Inner_Data_Data.Marshal(b, m, deterministic)
}
func (dst *Client_DH_Inner_Data_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client_DH_Inner_Data_Data.Merge(dst, src)
}
func (m *Client_DH_Inner_Data_Data) XXX_Size() int {
	return xxx_messageInfo_Client_DH_Inner_Data_Data.Size(m)
}
func (m *Client_DH_Inner_Data_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Client_DH_Inner_Data_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Client_DH_Inner_Data_Data proto.InternalMessageInfo

func (m *Client_DH_Inner_Data_Data) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *Client_DH_Inner_Data_Data) GetServerNonce() []byte {
	if m != nil {
		return m.ServerNonce
	}
	return nil
}

func (m *Client_DH_Inner_Data_Data) GetRetryId() int64 {
	if m != nil {
		return m.RetryId
	}
	return 0
}

func (m *Client_DH_Inner_Data_Data) GetGB() string {
	if m != nil {
		return m.GB
	}
	return ""
}

type Client_DH_Inner_Data struct {
	Constructor          TLConstructor              `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2                *Client_DH_Inner_Data_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Client_DH_Inner_Data) Reset()         { *m = Client_DH_Inner_Data{} }
func (m *Client_DH_Inner_Data) String() string { return proto.CompactTextString(m) }
func (*Client_DH_Inner_Data) ProtoMessage()    {}
func (*Client_DH_Inner_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{27}
}
func (m *Client_DH_Inner_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client_DH_Inner_Data.Unmarshal(m, b)
}
func (m *Client_DH_Inner_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client_DH_Inner_Data.Marshal(b, m, deterministic)
}
func (dst *Client_DH_Inner_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client_DH_Inner_Data.Merge(dst, src)
}
func (m *Client_DH_Inner_Data) XXX_Size() int {
	return xxx_messageInfo_Client_DH_Inner_Data.Size(m)
}
func (m *Client_DH_Inner_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Client_DH_Inner_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Client_DH_Inner_Data proto.InternalMessageInfo

func (m *Client_DH_Inner_Data) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *Client_DH_Inner_Data) GetData2() *Client_DH_Inner_Data_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// client_DH_inner_data#6643b654 nonce:int128 server_nonce:int128 retry_id:long g_b:string = Client_DH_Inner_Data;
type TLClient_DHInnerData struct {
	Data2                *Client_DH_Inner_Data_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *TLClient_DHInnerData) Reset()         { *m = TLClient_DHInnerData{} }
func (m *TLClient_DHInnerData) String() string { return proto.CompactTextString(m) }
func (*TLClient_DHInnerData) ProtoMessage()    {}
func (*TLClient_DHInnerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_handshake_48b66c9527610044, []int{28}
}
func (m *TLClient_DHInnerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLClient_DHInnerData.Unmarshal(m, b)
}
func (m *TLClient_DHInnerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLClient_DHInnerData.Marshal(b, m, deterministic)
}
func (dst *TLClient_DHInnerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLClient_DHInnerData.Merge(dst, src)
}
func (m *TLClient_DHInnerData) XXX_Size() int {
	return xxx_messageInfo_TLClient_DHInnerData.Size(m)
}
func (m *TLClient_DHInnerData) XXX_DiscardUnknown() {
	xxx_messageInfo_TLClient_DHInnerData.DiscardUnknown(m)
}

var xxx_messageInfo_TLClient_DHInnerData proto.InternalMessageInfo

func (m *TLClient_DHInnerData) GetData2() *Client_DH_Inner_Data_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

func init() {
	proto.RegisterType((*SetClient_DHParamsAnswer_Data)(nil), "mtproto.Set_client_DH_params_answer_Data")
	proto.RegisterType((*SetClient_DHParamsAnswer)(nil), "mtproto.Set_client_DH_params_answer")
	proto.RegisterType((*TLDhGenOk)(nil), "mtproto.TL_dh_gen_ok")
	proto.RegisterType((*TLDhGenRetry)(nil), "mtproto.TL_dh_gen_retry")
	proto.RegisterType((*TLDhGenFail)(nil), "mtproto.TL_dh_gen_fail")
	proto.RegisterType((*DestroyAuthKeyRes_Data)(nil), "mtproto.DestroyAuthKeyRes_Data")
	proto.RegisterType((*DestroyAuthKeyRes)(nil), "mtproto.DestroyAuthKeyRes")
	proto.RegisterType((*TLDestroyAuthKeyOk)(nil), "mtproto.TL_destroy_auth_key_ok")
	proto.RegisterType((*TLDestroyAuthKeyNone)(nil), "mtproto.TL_destroy_auth_key_none")
	proto.RegisterType((*TLDestroyAuthKeyFail)(nil), "mtproto.TL_destroy_auth_key_fail")
	proto.RegisterType((*ResPQ_Data)(nil), "mtproto.ResPQ_Data")
	proto.RegisterType((*ResPQ)(nil), "mtproto.ResPQ")
	proto.RegisterType((*TLResPQ)(nil), "mtproto.TL_resPQ")
	proto.RegisterType((*P_QInnerData_Data)(nil), "mtproto.P_Q_inner_data_Data")
	proto.RegisterType((*P_QInnerData)(nil), "mtproto.P_Q_inner_data")
	proto.RegisterType((*TLPQInnerData)(nil), "mtproto.TL_p_q_inner_data")
	proto.RegisterType((*TLPQInnerDataDc)(nil), "mtproto.TL_p_q_inner_data_dc")
	proto.RegisterType((*TLPQInnerDataTemp)(nil), "mtproto.TL_p_q_inner_data_temp")
	proto.RegisterType((*TLPQInnerDataTempDc)(nil), "mtproto.TL_p_q_inner_data_temp_dc")
	proto.RegisterType((*Server_DH_Params_Data)(nil), "mtproto.Server_DH_Params_Data")
	proto.RegisterType((*Server_DH_Params)(nil), "mtproto.Server_DH_Params")
	proto.RegisterType((*TLServer_DHParamsFail)(nil), "mtproto.TL_server_DH_params_fail")
	proto.RegisterType((*TLServer_DHParamsOk)(nil), "mtproto.TL_server_DH_params_ok")
	proto.RegisterType((*Server_DHInnerData_Data)(nil), "mtproto.Server_DH_inner_data_Data")
	proto.RegisterType((*Server_DHInnerData)(nil), "mtproto.Server_DH_inner_data")
	proto.RegisterType((*TLServer_DHInnerData)(nil), "mtproto.TL_server_DH_inner_data")
	proto.RegisterType((*Client_DH_Inner_Data_Data)(nil), "mtproto.Client_DH_Inner_Data_Data")
	proto.RegisterType((*Client_DH_Inner_Data)(nil), "mtproto.Client_DH_Inner_Data")
	proto.RegisterType((*TLClient_DHInnerData)(nil), "mtproto.TL_client_DH_inner_data")
}

func init() {
	proto.RegisterFile("schema.tl.handshake.proto", fileDescriptor_schema_tl_handshake_48b66c9527610044)
}

var fileDescriptor_schema_tl_handshake_48b66c9527610044 = []byte{
	// 869 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x51, 0x6f, 0xe3, 0x44,
	0x10, 0xd6, 0x26, 0x4d, 0x93, 0x4c, 0x43, 0x7a, 0xe7, 0xeb, 0x15, 0x87, 0xc0, 0x5d, 0xb0, 0x10,
	0x4a, 0x5f, 0x22, 0x91, 0x70, 0xd2, 0xbd, 0xa1, 0xb6, 0x11, 0xa4, 0x5c, 0xb8, 0x4b, 0xdc, 0xbc,
	0xaf, 0x1c, 0x7b, 0xb1, 0xad, 0xc4, 0x6b, 0x67, 0xbd, 0xa1, 0xe4, 0x05, 0x21, 0xc4, 0x13, 0xbf,
	0x00, 0xf1, 0xc6, 0x2f, 0xe0, 0x5f, 0xf0, 0x07, 0xf8, 0x43, 0xc8, 0x6b, 0xc7, 0x8e, 0x6b, 0xdf,
	0x15, 0x6c, 0x78, 0xf3, 0xce, 0x7c, 0xf3, 0x79, 0xe6, 0x9b, 0xdd, 0xd9, 0x85, 0x8e, 0xaf, 0x5b,
	0xc4, 0xd1, 0x06, 0x7c, 0x3d, 0xb0, 0x34, 0x6a, 0xf8, 0x96, 0xb6, 0x22, 0x03, 0x8f, 0xb9, 0xdc,
	0x95, 0xea, 0x0e, 0x17, 0x1f, 0x1f, 0x3c, 0x4d, 0x30, 0x3a, 0xd3, 0x47, 0xc3, 0xd0, 0xaf, 0xfc,
	0x85, 0xa0, 0x77, 0x4b, 0x38, 0xd6, 0xd7, 0x36, 0xa1, 0x1c, 0x8f, 0x27, 0xd8, 0xd3, 0x98, 0xe6,
	0xf8, 0x58, 0xa3, 0xfe, 0x1d, 0x61, 0x78, 0xac, 0x71, 0x4d, 0x3a, 0x83, 0x1a, 0x75, 0xa9, 0x4e,
	0x64, 0xd4, 0x43, 0xfd, 0x96, 0x1a, 0x2e, 0xa4, 0x8f, 0xa1, 0xe5, 0x13, 0xf6, 0x1d, 0x61, 0x38,
	0x74, 0x56, 0x84, 0xf3, 0x24, 0xb4, 0xbd, 0x16, 0x90, 0x4f, 0xe1, 0x94, 0x92, 0xbb, 0xd0, 0x8f,
	0x2d, 0xcd, 0xb7, 0x3e, 0x93, 0xab, 0x02, 0xf5, 0x1e, 0x25, 0x77, 0x02, 0x32, 0x09, 0x8c, 0x59,
	0xdc, 0x50, 0x3e, 0xca, 0xe2, 0x86, 0x59, 0xdc, 0x48, 0xae, 0x65, 0x71, 0x23, 0xe5, 0x57, 0x04,
	0xdd, 0x77, 0x54, 0x25, 0xbd, 0x84, 0x13, 0xdd, 0xa5, 0x3e, 0x67, 0x5b, 0x9d, 0xbb, 0x4c, 0x94,
	0xd5, 0x1e, 0x9e, 0x0f, 0x22, 0xad, 0x06, 0x8b, 0xe9, 0x75, 0xe2, 0x55, 0x0f, 0xa1, 0xd2, 0x17,
	0x50, 0x33, 0x34, 0xae, 0x0d, 0x45, 0xb5, 0x27, 0xc3, 0x8b, 0x38, 0xe6, 0x21, 0x11, 0xd5, 0x30,
	0x4e, 0x79, 0x03, 0xad, 0xc5, 0x14, 0x1b, 0x16, 0x36, 0x09, 0xc5, 0xee, 0xaa, 0x3c, 0xa1, 0x0a,
	0xa7, 0x09, 0x21, 0x23, 0x9c, 0xed, 0xca, 0x73, 0xce, 0xa1, 0x9d, 0x70, 0x7e, 0xab, 0xd9, 0xeb,
	0xf2, 0x94, 0x32, 0x9c, 0x8f, 0x89, 0xcf, 0x99, 0xbb, 0xbb, 0xdc, 0x72, 0xeb, 0x15, 0xd9, 0xa9,
	0xc4, 0x17, 0x00, 0xe5, 0x67, 0x04, 0x8f, 0x33, 0xae, 0x12, 0x2d, 0x7a, 0x91, 0x4e, 0xf5, 0x79,
	0x1c, 0x93, 0xff, 0xff, 0xa4, 0x31, 0xe7, 0x41, 0xcd, 0x21, 0x06, 0x6b, 0x5b, 0x6e, 0xe1, 0x15,
	0xd9, 0x05, 0x2d, 0x2a, 0x48, 0x38, 0x07, 0x39, 0x8f, 0x90, 0xba, 0x94, 0xfc, 0xc7, 0x94, 0xa2,
	0x43, 0x05, 0x29, 0x7f, 0x43, 0x00, 0x2a, 0xf1, 0x67, 0xf3, 0x92, 0x47, 0xbd, 0x0d, 0x15, 0x6f,
	0x23, 0x4e, 0x77, 0x53, 0xad, 0x78, 0x1b, 0xe9, 0x1a, 0x9e, 0x45, 0x21, 0xde, 0x76, 0xb9, 0xb6,
	0xf5, 0x30, 0x51, 0x9b, 0x9a, 0x84, 0x79, 0xcc, 0xa6, 0xdc, 0x97, 0x8f, 0x7a, 0xd5, 0x7e, 0x55,
	0xed, 0x86, 0xa8, 0x99, 0x00, 0xbd, 0x22, 0xbb, 0x2f, 0x0f, 0x20, 0xca, 0x1a, 0x6a, 0x22, 0xb7,
	0x12, 0xbb, 0xe1, 0x22, 0x2d, 0xcb, 0x93, 0x38, 0x26, 0x29, 0x7a, 0x2f, 0xc5, 0x0b, 0x68, 0x2c,
	0xa6, 0x98, 0x89, 0x1f, 0xfe, 0x8b, 0xb0, 0x3f, 0x11, 0x3c, 0x99, 0xe1, 0x39, 0xb6, 0x29, 0x25,
	0x0c, 0x07, 0xb6, 0x50, 0xca, 0x50, 0x11, 0x14, 0x2b, 0xd2, 0x02, 0xe4, 0x09, 0xba, 0xa6, 0x8a,
	0xbc, 0x60, 0xb5, 0x97, 0x0b, 0x6d, 0x12, 0xd9, 0x8f, 0xde, 0x25, 0x7b, 0x2d, 0x2b, 0x7b, 0x17,
	0x9a, 0xf1, 0x44, 0x94, 0x8f, 0x85, 0xbf, 0xb1, 0x9f, 0x85, 0x41, 0x06, 0x86, 0x2e, 0xd7, 0x7b,
	0xa8, 0x5f, 0x53, 0x2b, 0x86, 0x2e, 0x7d, 0x04, 0x40, 0xbe, 0xf7, 0x6c, 0x46, 0x7c, 0x6c, 0x53,
	0xb9, 0x21, 0xec, 0xcd, 0xc8, 0x72, 0x43, 0x95, 0x1f, 0xa0, 0x9d, 0xae, 0xa3, 0x84, 0xec, 0xc3,
	0xb4, 0x7e, 0x1f, 0xc6, 0x31, 0x39, 0x4a, 0xed, 0x85, 0xfc, 0x0a, 0x1e, 0x2f, 0xa6, 0xd8, 0xc3,
	0x9b, 0xc3, 0x14, 0x8a, 0x10, 0x7d, 0x0d, 0x67, 0x19, 0x22, 0x6c, 0xe8, 0x85, 0xb8, 0xa6, 0x62,
	0x2c, 0xdc, 0xe3, 0xe2, 0xc4, 0xf1, 0x0a, 0xb1, 0xbd, 0x81, 0x4e, 0x3e, 0x5b, 0xd1, 0xf4, 0x7e,
	0x47, 0xf0, 0xf4, 0x36, 0xdc, 0x23, 0xe3, 0x09, 0x9e, 0x85, 0xe3, 0xb7, 0xdc, 0x49, 0xfe, 0x04,
	0xda, 0xe9, 0x4b, 0x36, 0xba, 0xb3, 0x5b, 0x87, 0x77, 0xac, 0x74, 0x01, 0x8f, 0x08, 0xd5, 0xd9,
	0xce, 0xe3, 0xc4, 0x88, 0xe6, 0xbd, 0xd8, 0xbc, 0x4d, 0xf5, 0x34, 0xb6, 0x5f, 0x0a, 0xb3, 0xf2,
	0x13, 0x82, 0x47, 0xf7, 0x73, 0x2c, 0xb1, 0xb5, 0x3e, 0x4f, 0xcb, 0xf4, 0xec, 0xe0, 0x2a, 0xca,
	0xd1, 0x61, 0x2f, 0xd4, 0x4c, 0x8c, 0x4e, 0x3f, 0x86, 0x44, 0x37, 0x95, 0x18, 0x9d, 0xc5, 0x18,
	0x5f, 0x8b, 0x9d, 0x91, 0x61, 0x74, 0x57, 0x05, 0xf9, 0xfe, 0x40, 0xd0, 0x49, 0x00, 0xf7, 0xa7,
	0x49, 0xe1, 0x76, 0xb6, 0x00, 0x99, 0xa2, 0x83, 0x35, 0x15, 0x99, 0x52, 0x07, 0x1a, 0x86, 0x85,
	0x3d, 0x66, 0x3b, 0x24, 0x6a, 0x57, 0xdd, 0xb0, 0x66, 0xc1, 0x52, 0x3a, 0x85, 0xaa, 0x89, 0x35,
	0x31, 0x64, 0x9a, 0x6a, 0xc5, 0xbc, 0x94, 0x9e, 0x43, 0x44, 0x84, 0x79, 0x00, 0x3f, 0x16, 0x1c,
	0x10, 0x9a, 0x16, 0xb6, 0x43, 0x94, 0x5f, 0x10, 0x9c, 0xe5, 0x65, 0x5c, 0xa2, 0xb9, 0x2f, 0xd3,
	0xd2, 0x29, 0x39, 0xd2, 0xbd, 0xe5, 0x24, 0xdc, 0xc2, 0xfb, 0xa9, 0x76, 0xa4, 0xd2, 0x29, 0x4a,
	0xfa, 0x23, 0x82, 0xce, 0x75, 0xfc, 0xba, 0xb9, 0x11, 0xa0, 0x71, 0xf9, 0x9e, 0x74, 0xa0, 0x21,
	0x5e, 0x6a, 0xd8, 0x36, 0x44, 0x6b, 0xaa, 0x6a, 0x5d, 0xac, 0x6f, 0x8c, 0xb0, 0x0b, 0xcb, 0xa8,
	0x37, 0x15, 0xf3, 0x4a, 0x88, 0x9c, 0x97, 0xc2, 0xff, 0x21, 0xf2, 0x5b, 0x4b, 0x4d, 0x8b, 0x9c,
	0xbc, 0xf7, 0xfe, 0x89, 0xc8, 0x0f, 0x91, 0x5e, 0xf5, 0xa1, 0xab, 0xbb, 0xce, 0x80, 0x92, 0xe5,
	0x76, 0xad, 0xd9, 0xce, 0x80, 0x50, 0xd3, 0xa6, 0x64, 0x1f, 0x7f, 0x55, 0xff, 0x66, 0x31, 0x0b,
	0x3e, 0x26, 0x95, 0xe5, 0xb1, 0xb0, 0x8c, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x18, 0xd9, 0xab,
	0x60, 0xf1, 0x0c, 0x00, 0x00,
}
