// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.tl.proto

package mtproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// /////////////////////////////////////////////////////////////////////////////
// ConnectToServer <--
//  + TL_sync_connectToSessionServer
//
type ConnectToServer_Data struct {
	SyncServerId         int32    `protobuf:"varint,1,opt,name=sync_server_id,json=syncServerId,proto3" json:"sync_server_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectToServer_Data) Reset()         { *m = ConnectToServer_Data{} }
func (m *ConnectToServer_Data) String() string { return proto.CompactTextString(m) }
func (*ConnectToServer_Data) ProtoMessage()    {}
func (*ConnectToServer_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_tl_f5d2345e23df3c9b, []int{0}
}
func (m *ConnectToServer_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectToServer_Data.Unmarshal(m, b)
}
func (m *ConnectToServer_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectToServer_Data.Marshal(b, m, deterministic)
}
func (dst *ConnectToServer_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectToServer_Data.Merge(dst, src)
}
func (m *ConnectToServer_Data) XXX_Size() int {
	return xxx_messageInfo_ConnectToServer_Data.Size(m)
}
func (m *ConnectToServer_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectToServer_Data.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectToServer_Data proto.InternalMessageInfo

func (m *ConnectToServer_Data) GetSyncServerId() int32 {
	if m != nil {
		return m.SyncServerId
	}
	return 0
}

type ConnectToServer struct {
	Constructor          TLConstructor         `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2                *ConnectToServer_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ConnectToServer) Reset()         { *m = ConnectToServer{} }
func (m *ConnectToServer) String() string { return proto.CompactTextString(m) }
func (*ConnectToServer) ProtoMessage()    {}
func (*ConnectToServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_tl_f5d2345e23df3c9b, []int{1}
}
func (m *ConnectToServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectToServer.Unmarshal(m, b)
}
func (m *ConnectToServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectToServer.Marshal(b, m, deterministic)
}
func (dst *ConnectToServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectToServer.Merge(dst, src)
}
func (m *ConnectToServer) XXX_Size() int {
	return xxx_messageInfo_ConnectToServer.Size(m)
}
func (m *ConnectToServer) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectToServer.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectToServer proto.InternalMessageInfo

func (m *ConnectToServer) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *ConnectToServer) GetData2() *ConnectToServer_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// sync.connectToSessionServer sync_server_id:int = ConnectToServer;
type TLSyncConnectToSessionServer struct {
	Data2                *ConnectToServer_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TLSyncConnectToSessionServer) Reset()         { *m = TLSyncConnectToSessionServer{} }
func (m *TLSyncConnectToSessionServer) String() string { return proto.CompactTextString(m) }
func (*TLSyncConnectToSessionServer) ProtoMessage()    {}
func (*TLSyncConnectToSessionServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_tl_f5d2345e23df3c9b, []int{2}
}
func (m *TLSyncConnectToSessionServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLSyncConnectToSessionServer.Unmarshal(m, b)
}
func (m *TLSyncConnectToSessionServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLSyncConnectToSessionServer.Marshal(b, m, deterministic)
}
func (dst *TLSyncConnectToSessionServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLSyncConnectToSessionServer.Merge(dst, src)
}
func (m *TLSyncConnectToSessionServer) XXX_Size() int {
	return xxx_messageInfo_TLSyncConnectToSessionServer.Size(m)
}
func (m *TLSyncConnectToSessionServer) XXX_DiscardUnknown() {
	xxx_messageInfo_TLSyncConnectToSessionServer.DiscardUnknown(m)
}

var xxx_messageInfo_TLSyncConnectToSessionServer proto.InternalMessageInfo

func (m *TLSyncConnectToSessionServer) GetData2() *ConnectToServer_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// ServerConnected <--
//  + TL_sync_sessionServerConnected
//
type ServerConnected_Data struct {
	SessionServerId      int32    `protobuf:"varint,1,opt,name=session_server_id,json=sessionServerId,proto3" json:"session_server_id,omitempty"`
	ServerName           string   `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerConnected_Data) Reset()         { *m = ServerConnected_Data{} }
func (m *ServerConnected_Data) String() string { return proto.CompactTextString(m) }
func (*ServerConnected_Data) ProtoMessage()    {}
func (*ServerConnected_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_tl_f5d2345e23df3c9b, []int{3}
}
func (m *ServerConnected_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerConnected_Data.Unmarshal(m, b)
}
func (m *ServerConnected_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerConnected_Data.Marshal(b, m, deterministic)
}
func (dst *ServerConnected_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerConnected_Data.Merge(dst, src)
}
func (m *ServerConnected_Data) XXX_Size() int {
	return xxx_messageInfo_ServerConnected_Data.Size(m)
}
func (m *ServerConnected_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerConnected_Data.DiscardUnknown(m)
}

var xxx_messageInfo_ServerConnected_Data proto.InternalMessageInfo

func (m *ServerConnected_Data) GetSessionServerId() int32 {
	if m != nil {
		return m.SessionServerId
	}
	return 0
}

func (m *ServerConnected_Data) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

type ServerConnected struct {
	Constructor          TLConstructor         `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2                *ServerConnected_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ServerConnected) Reset()         { *m = ServerConnected{} }
func (m *ServerConnected) String() string { return proto.CompactTextString(m) }
func (*ServerConnected) ProtoMessage()    {}
func (*ServerConnected) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_tl_f5d2345e23df3c9b, []int{4}
}
func (m *ServerConnected) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerConnected.Unmarshal(m, b)
}
func (m *ServerConnected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerConnected.Marshal(b, m, deterministic)
}
func (dst *ServerConnected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerConnected.Merge(dst, src)
}
func (m *ServerConnected) XXX_Size() int {
	return xxx_messageInfo_ServerConnected.Size(m)
}
func (m *ServerConnected) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerConnected.DiscardUnknown(m)
}

var xxx_messageInfo_ServerConnected proto.InternalMessageInfo

func (m *ServerConnected) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *ServerConnected) GetData2() *ServerConnected_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// sync.sessionServerConnected session_server_id:int server_name:string = ServerConnected;
type TLSyncSessionServerConnected struct {
	Data2                *ServerConnected_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TLSyncSessionServerConnected) Reset()         { *m = TLSyncSessionServerConnected{} }
func (m *TLSyncSessionServerConnected) String() string { return proto.CompactTextString(m) }
func (*TLSyncSessionServerConnected) ProtoMessage()    {}
func (*TLSyncSessionServerConnected) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_tl_f5d2345e23df3c9b, []int{5}
}
func (m *TLSyncSessionServerConnected) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLSyncSessionServerConnected.Unmarshal(m, b)
}
func (m *TLSyncSessionServerConnected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLSyncSessionServerConnected.Marshal(b, m, deterministic)
}
func (dst *TLSyncSessionServerConnected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLSyncSessionServerConnected.Merge(dst, src)
}
func (m *TLSyncSessionServerConnected) XXX_Size() int {
	return xxx_messageInfo_TLSyncSessionServerConnected.Size(m)
}
func (m *TLSyncSessionServerConnected) XXX_DiscardUnknown() {
	xxx_messageInfo_TLSyncSessionServerConnected.DiscardUnknown(m)
}

var xxx_messageInfo_TLSyncSessionServerConnected proto.InternalMessageInfo

func (m *TLSyncSessionServerConnected) GetData2() *ServerConnected_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// PushData <--
//  + TL_sync_pushUpdatesData
//  + TL_sync_pushRpcResultData
//
type PushData_Data struct {
	AuthKeyId            int64    `protobuf:"varint,1,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	Updates              *Updates `protobuf:"bytes,2,opt,name=updates,proto3" json:"updates,omitempty"`
	ClientReqMsgId       int64    `protobuf:"varint,3,opt,name=client_req_msg_id,json=clientReqMsgId,proto3" json:"client_req_msg_id,omitempty"`
	Result               []byte   `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushData_Data) Reset()         { *m = PushData_Data{} }
func (m *PushData_Data) String() string { return proto.CompactTextString(m) }
func (*PushData_Data) ProtoMessage()    {}
func (*PushData_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_tl_f5d2345e23df3c9b, []int{6}
}
func (m *PushData_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushData_Data.Unmarshal(m, b)
}
func (m *PushData_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushData_Data.Marshal(b, m, deterministic)
}
func (dst *PushData_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushData_Data.Merge(dst, src)
}
func (m *PushData_Data) XXX_Size() int {
	return xxx_messageInfo_PushData_Data.Size(m)
}
func (m *PushData_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_PushData_Data.DiscardUnknown(m)
}

var xxx_messageInfo_PushData_Data proto.InternalMessageInfo

func (m *PushData_Data) GetAuthKeyId() int64 {
	if m != nil {
		return m.AuthKeyId
	}
	return 0
}

func (m *PushData_Data) GetUpdates() *Updates {
	if m != nil {
		return m.Updates
	}
	return nil
}

func (m *PushData_Data) GetClientReqMsgId() int64 {
	if m != nil {
		return m.ClientReqMsgId
	}
	return 0
}

func (m *PushData_Data) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type PushData struct {
	Constructor          TLConstructor  `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2                *PushData_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PushData) Reset()         { *m = PushData{} }
func (m *PushData) String() string { return proto.CompactTextString(m) }
func (*PushData) ProtoMessage()    {}
func (*PushData) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_tl_f5d2345e23df3c9b, []int{7}
}
func (m *PushData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushData.Unmarshal(m, b)
}
func (m *PushData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushData.Marshal(b, m, deterministic)
}
func (dst *PushData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushData.Merge(dst, src)
}
func (m *PushData) XXX_Size() int {
	return xxx_messageInfo_PushData.Size(m)
}
func (m *PushData) XXX_DiscardUnknown() {
	xxx_messageInfo_PushData.DiscardUnknown(m)
}

var xxx_messageInfo_PushData proto.InternalMessageInfo

func (m *PushData) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *PushData) GetData2() *PushData_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// sync.pushUpdatesData auth_key_id:long updates:Updates = PushData;
type TLSyncPushUpdatesData struct {
	Data2                *PushData_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TLSyncPushUpdatesData) Reset()         { *m = TLSyncPushUpdatesData{} }
func (m *TLSyncPushUpdatesData) String() string { return proto.CompactTextString(m) }
func (*TLSyncPushUpdatesData) ProtoMessage()    {}
func (*TLSyncPushUpdatesData) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_tl_f5d2345e23df3c9b, []int{8}
}
func (m *TLSyncPushUpdatesData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLSyncPushUpdatesData.Unmarshal(m, b)
}
func (m *TLSyncPushUpdatesData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLSyncPushUpdatesData.Marshal(b, m, deterministic)
}
func (dst *TLSyncPushUpdatesData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLSyncPushUpdatesData.Merge(dst, src)
}
func (m *TLSyncPushUpdatesData) XXX_Size() int {
	return xxx_messageInfo_TLSyncPushUpdatesData.Size(m)
}
func (m *TLSyncPushUpdatesData) XXX_DiscardUnknown() {
	xxx_messageInfo_TLSyncPushUpdatesData.DiscardUnknown(m)
}

var xxx_messageInfo_TLSyncPushUpdatesData proto.InternalMessageInfo

func (m *TLSyncPushUpdatesData) GetData2() *PushData_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// sync.pushRpcResultData auth_key_id:long client_req_msg_id:long result:bytes = PushData;
type TLSyncPushRpcResultData struct {
	Data2                *PushData_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TLSyncPushRpcResultData) Reset()         { *m = TLSyncPushRpcResultData{} }
func (m *TLSyncPushRpcResultData) String() string { return proto.CompactTextString(m) }
func (*TLSyncPushRpcResultData) ProtoMessage()    {}
func (*TLSyncPushRpcResultData) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_tl_f5d2345e23df3c9b, []int{9}
}
func (m *TLSyncPushRpcResultData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLSyncPushRpcResultData.Unmarshal(m, b)
}
func (m *TLSyncPushRpcResultData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLSyncPushRpcResultData.Marshal(b, m, deterministic)
}
func (dst *TLSyncPushRpcResultData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLSyncPushRpcResultData.Merge(dst, src)
}
func (m *TLSyncPushRpcResultData) XXX_Size() int {
	return xxx_messageInfo_TLSyncPushRpcResultData.Size(m)
}
func (m *TLSyncPushRpcResultData) XXX_DiscardUnknown() {
	xxx_messageInfo_TLSyncPushRpcResultData.DiscardUnknown(m)
}

var xxx_messageInfo_TLSyncPushRpcResultData proto.InternalMessageInfo

func (m *TLSyncPushRpcResultData) GetData2() *PushData_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// sync.syncUpdates flags:# user_id:int auth_key_id:long server_id:flags.0?int not_me:flags.1?true updates:Updates = Bool;
type TLSyncSyncUpdates struct {
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthKeyId            int64    `protobuf:"varint,3,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	ServerId             int32    `protobuf:"varint,4,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	NotMe                bool     `protobuf:"varint,5,opt,name=not_me,json=notMe,proto3" json:"not_me,omitempty"`
	Updates              *Updates `protobuf:"bytes,6,opt,name=updates,proto3" json:"updates,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TLSyncSyncUpdates) Reset()         { *m = TLSyncSyncUpdates{} }
func (m *TLSyncSyncUpdates) String() string { return proto.CompactTextString(m) }
func (*TLSyncSyncUpdates) ProtoMessage()    {}
func (*TLSyncSyncUpdates) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_tl_f5d2345e23df3c9b, []int{10}
}
func (m *TLSyncSyncUpdates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLSyncSyncUpdates.Unmarshal(m, b)
}
func (m *TLSyncSyncUpdates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLSyncSyncUpdates.Marshal(b, m, deterministic)
}
func (dst *TLSyncSyncUpdates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLSyncSyncUpdates.Merge(dst, src)
}
func (m *TLSyncSyncUpdates) XXX_Size() int {
	return xxx_messageInfo_TLSyncSyncUpdates.Size(m)
}
func (m *TLSyncSyncUpdates) XXX_DiscardUnknown() {
	xxx_messageInfo_TLSyncSyncUpdates.DiscardUnknown(m)
}

var xxx_messageInfo_TLSyncSyncUpdates proto.InternalMessageInfo

func (m *TLSyncSyncUpdates) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *TLSyncSyncUpdates) GetAuthKeyId() int64 {
	if m != nil {
		return m.AuthKeyId
	}
	return 0
}

func (m *TLSyncSyncUpdates) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *TLSyncSyncUpdates) GetNotMe() bool {
	if m != nil {
		return m.NotMe
	}
	return false
}

func (m *TLSyncSyncUpdates) GetUpdates() *Updates {
	if m != nil {
		return m.Updates
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// sync.pushUpdates user_id:int updates:Updates = Bool;
type TLSyncPushUpdates struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Updates              *Updates `protobuf:"bytes,2,opt,name=updates,proto3" json:"updates,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TLSyncPushUpdates) Reset()         { *m = TLSyncPushUpdates{} }
func (m *TLSyncPushUpdates) String() string { return proto.CompactTextString(m) }
func (*TLSyncPushUpdates) ProtoMessage()    {}
func (*TLSyncPushUpdates) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_tl_f5d2345e23df3c9b, []int{11}
}
func (m *TLSyncPushUpdates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLSyncPushUpdates.Unmarshal(m, b)
}
func (m *TLSyncPushUpdates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLSyncPushUpdates.Marshal(b, m, deterministic)
}
func (dst *TLSyncPushUpdates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLSyncPushUpdates.Merge(dst, src)
}
func (m *TLSyncPushUpdates) XXX_Size() int {
	return xxx_messageInfo_TLSyncPushUpdates.Size(m)
}
func (m *TLSyncPushUpdates) XXX_DiscardUnknown() {
	xxx_messageInfo_TLSyncPushUpdates.DiscardUnknown(m)
}

var xxx_messageInfo_TLSyncPushUpdates proto.InternalMessageInfo

func (m *TLSyncPushUpdates) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *TLSyncPushUpdates) GetUpdates() *Updates {
	if m != nil {
		return m.Updates
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// sync.pushChannelUpdates channel_id:int exclude_user_id:int updates:Updates = Bool;
type TLSyncPushChannelUpdates struct {
	ChannelId            int32    `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ExcludeUserId        int32    `protobuf:"varint,2,opt,name=exclude_user_id,json=excludeUserId,proto3" json:"exclude_user_id,omitempty"`
	Updates              *Updates `protobuf:"bytes,3,opt,name=updates,proto3" json:"updates,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TLSyncPushChannelUpdates) Reset()         { *m = TLSyncPushChannelUpdates{} }
func (m *TLSyncPushChannelUpdates) String() string { return proto.CompactTextString(m) }
func (*TLSyncPushChannelUpdates) ProtoMessage()    {}
func (*TLSyncPushChannelUpdates) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_tl_f5d2345e23df3c9b, []int{12}
}
func (m *TLSyncPushChannelUpdates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLSyncPushChannelUpdates.Unmarshal(m, b)
}
func (m *TLSyncPushChannelUpdates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLSyncPushChannelUpdates.Marshal(b, m, deterministic)
}
func (dst *TLSyncPushChannelUpdates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLSyncPushChannelUpdates.Merge(dst, src)
}
func (m *TLSyncPushChannelUpdates) XXX_Size() int {
	return xxx_messageInfo_TLSyncPushChannelUpdates.Size(m)
}
func (m *TLSyncPushChannelUpdates) XXX_DiscardUnknown() {
	xxx_messageInfo_TLSyncPushChannelUpdates.DiscardUnknown(m)
}

var xxx_messageInfo_TLSyncPushChannelUpdates proto.InternalMessageInfo

func (m *TLSyncPushChannelUpdates) GetChannelId() int32 {
	if m != nil {
		return m.ChannelId
	}
	return 0
}

func (m *TLSyncPushChannelUpdates) GetExcludeUserId() int32 {
	if m != nil {
		return m.ExcludeUserId
	}
	return 0
}

func (m *TLSyncPushChannelUpdates) GetUpdates() *Updates {
	if m != nil {
		return m.Updates
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// sync.pushRpcResult server_id:int auth_key_id:long req_msg_id:long result:bytes = Bool;
type TLSyncPushRpcResult struct {
	ServerId             int32    `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	AuthKeyId            int64    `protobuf:"varint,2,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	ReqMsgId             int64    `protobuf:"varint,3,opt,name=req_msg_id,json=reqMsgId,proto3" json:"req_msg_id,omitempty"`
	Result               []byte   `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TLSyncPushRpcResult) Reset()         { *m = TLSyncPushRpcResult{} }
func (m *TLSyncPushRpcResult) String() string { return proto.CompactTextString(m) }
func (*TLSyncPushRpcResult) ProtoMessage()    {}
func (*TLSyncPushRpcResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_tl_f5d2345e23df3c9b, []int{13}
}
func (m *TLSyncPushRpcResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLSyncPushRpcResult.Unmarshal(m, b)
}
func (m *TLSyncPushRpcResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLSyncPushRpcResult.Marshal(b, m, deterministic)
}
func (dst *TLSyncPushRpcResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLSyncPushRpcResult.Merge(dst, src)
}
func (m *TLSyncPushRpcResult) XXX_Size() int {
	return xxx_messageInfo_TLSyncPushRpcResult.Size(m)
}
func (m *TLSyncPushRpcResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TLSyncPushRpcResult.DiscardUnknown(m)
}

var xxx_messageInfo_TLSyncPushRpcResult proto.InternalMessageInfo

func (m *TLSyncPushRpcResult) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *TLSyncPushRpcResult) GetAuthKeyId() int64 {
	if m != nil {
		return m.AuthKeyId
	}
	return 0
}

func (m *TLSyncPushRpcResult) GetReqMsgId() int64 {
	if m != nil {
		return m.ReqMsgId
	}
	return 0
}

func (m *TLSyncPushRpcResult) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// sync.getState auth_key_id:long user_id:int = updates.State;
type TLSyncGetState struct {
	AuthKeyId            int64    `protobuf:"varint,1,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TLSyncGetState) Reset()         { *m = TLSyncGetState{} }
func (m *TLSyncGetState) String() string { return proto.CompactTextString(m) }
func (*TLSyncGetState) ProtoMessage()    {}
func (*TLSyncGetState) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_tl_f5d2345e23df3c9b, []int{14}
}
func (m *TLSyncGetState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLSyncGetState.Unmarshal(m, b)
}
func (m *TLSyncGetState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLSyncGetState.Marshal(b, m, deterministic)
}
func (dst *TLSyncGetState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLSyncGetState.Merge(dst, src)
}
func (m *TLSyncGetState) XXX_Size() int {
	return xxx_messageInfo_TLSyncGetState.Size(m)
}
func (m *TLSyncGetState) XXX_DiscardUnknown() {
	xxx_messageInfo_TLSyncGetState.DiscardUnknown(m)
}

var xxx_messageInfo_TLSyncGetState proto.InternalMessageInfo

func (m *TLSyncGetState) GetAuthKeyId() int64 {
	if m != nil {
		return m.AuthKeyId
	}
	return 0
}

func (m *TLSyncGetState) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

// /////////////////////////////////////////////////////////////////////////////
// sync.getDifference flags:# auth_key_id:long user_id:int pts:int pts_total_limit:flags.0?int date:int qts:int = updates.Difference;
type TLSyncGetDifference struct {
	AuthKeyId            int64    `protobuf:"varint,2,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	UserId               int32    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pts                  int32    `protobuf:"varint,4,opt,name=pts,proto3" json:"pts,omitempty"`
	PtsTotalLimit        int32    `protobuf:"varint,5,opt,name=pts_total_limit,json=ptsTotalLimit,proto3" json:"pts_total_limit,omitempty"`
	Date                 int32    `protobuf:"varint,6,opt,name=date,proto3" json:"date,omitempty"`
	Qts                  int32    `protobuf:"varint,7,opt,name=qts,proto3" json:"qts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TLSyncGetDifference) Reset()         { *m = TLSyncGetDifference{} }
func (m *TLSyncGetDifference) String() string { return proto.CompactTextString(m) }
func (*TLSyncGetDifference) ProtoMessage()    {}
func (*TLSyncGetDifference) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_tl_f5d2345e23df3c9b, []int{15}
}
func (m *TLSyncGetDifference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLSyncGetDifference.Unmarshal(m, b)
}
func (m *TLSyncGetDifference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLSyncGetDifference.Marshal(b, m, deterministic)
}
func (dst *TLSyncGetDifference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLSyncGetDifference.Merge(dst, src)
}
func (m *TLSyncGetDifference) XXX_Size() int {
	return xxx_messageInfo_TLSyncGetDifference.Size(m)
}
func (m *TLSyncGetDifference) XXX_DiscardUnknown() {
	xxx_messageInfo_TLSyncGetDifference.DiscardUnknown(m)
}

var xxx_messageInfo_TLSyncGetDifference proto.InternalMessageInfo

func (m *TLSyncGetDifference) GetAuthKeyId() int64 {
	if m != nil {
		return m.AuthKeyId
	}
	return 0
}

func (m *TLSyncGetDifference) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *TLSyncGetDifference) GetPts() int32 {
	if m != nil {
		return m.Pts
	}
	return 0
}

func (m *TLSyncGetDifference) GetPtsTotalLimit() int32 {
	if m != nil {
		return m.PtsTotalLimit
	}
	return 0
}

func (m *TLSyncGetDifference) GetDate() int32 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *TLSyncGetDifference) GetQts() int32 {
	if m != nil {
		return m.Qts
	}
	return 0
}

// /////////////////////////////////////////////////////////////////////////////
// sync.getChannelDifference flags:# auth_key_id:long user_id:int force:flags.0?true channel:InputChannel filter:ChannelMessagesFilter pts:int limit:int = updates.ChannelDifference;
type TLSyncGetChannelDifference struct {
	AuthKeyId            int64                  `protobuf:"varint,2,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	UserId               int32                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Force                bool                   `protobuf:"varint,4,opt,name=force,proto3" json:"force,omitempty"`
	Channel              *InputChannel          `protobuf:"bytes,5,opt,name=channel,proto3" json:"channel,omitempty"`
	Filter               *ChannelMessagesFilter `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty"`
	Pts                  int32                  `protobuf:"varint,7,opt,name=pts,proto3" json:"pts,omitempty"`
	Limit                int32                  `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TLSyncGetChannelDifference) Reset()         { *m = TLSyncGetChannelDifference{} }
func (m *TLSyncGetChannelDifference) String() string { return proto.CompactTextString(m) }
func (*TLSyncGetChannelDifference) ProtoMessage()    {}
func (*TLSyncGetChannelDifference) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_tl_f5d2345e23df3c9b, []int{16}
}
func (m *TLSyncGetChannelDifference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLSyncGetChannelDifference.Unmarshal(m, b)
}
func (m *TLSyncGetChannelDifference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLSyncGetChannelDifference.Marshal(b, m, deterministic)
}
func (dst *TLSyncGetChannelDifference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLSyncGetChannelDifference.Merge(dst, src)
}
func (m *TLSyncGetChannelDifference) XXX_Size() int {
	return xxx_messageInfo_TLSyncGetChannelDifference.Size(m)
}
func (m *TLSyncGetChannelDifference) XXX_DiscardUnknown() {
	xxx_messageInfo_TLSyncGetChannelDifference.DiscardUnknown(m)
}

var xxx_messageInfo_TLSyncGetChannelDifference proto.InternalMessageInfo

func (m *TLSyncGetChannelDifference) GetAuthKeyId() int64 {
	if m != nil {
		return m.AuthKeyId
	}
	return 0
}

func (m *TLSyncGetChannelDifference) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *TLSyncGetChannelDifference) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

func (m *TLSyncGetChannelDifference) GetChannel() *InputChannel {
	if m != nil {
		return m.Channel
	}
	return nil
}

func (m *TLSyncGetChannelDifference) GetFilter() *ChannelMessagesFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *TLSyncGetChannelDifference) GetPts() int32 {
	if m != nil {
		return m.Pts
	}
	return 0
}

func (m *TLSyncGetChannelDifference) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func init() {
	proto.RegisterType((*ConnectToServer_Data)(nil), "mtproto.ConnectToServer_Data")
	proto.RegisterType((*ConnectToServer)(nil), "mtproto.ConnectToServer")
	proto.RegisterType((*TLSyncConnectToSessionServer)(nil), "mtproto.TL_sync_connectToSessionServer")
	proto.RegisterType((*ServerConnected_Data)(nil), "mtproto.ServerConnected_Data")
	proto.RegisterType((*ServerConnected)(nil), "mtproto.ServerConnected")
	proto.RegisterType((*TLSyncSessionServerConnected)(nil), "mtproto.TL_sync_sessionServerConnected")
	proto.RegisterType((*PushData_Data)(nil), "mtproto.PushData_Data")
	proto.RegisterType((*PushData)(nil), "mtproto.PushData")
	proto.RegisterType((*TLSyncPushUpdatesData)(nil), "mtproto.TL_sync_pushUpdatesData")
	proto.RegisterType((*TLSyncPushRpcResultData)(nil), "mtproto.TL_sync_pushRpcResultData")
	proto.RegisterType((*TLSyncSyncUpdates)(nil), "mtproto.TL_sync_syncUpdates")
	proto.RegisterType((*TLSyncPushUpdates)(nil), "mtproto.TL_sync_pushUpdates")
	proto.RegisterType((*TLSyncPushChannelUpdates)(nil), "mtproto.TL_sync_pushChannelUpdates")
	proto.RegisterType((*TLSyncPushRpcResult)(nil), "mtproto.TL_sync_pushRpcResult")
	proto.RegisterType((*TLSyncGetState)(nil), "mtproto.TL_sync_getState")
	proto.RegisterType((*TLSyncGetDifference)(nil), "mtproto.TL_sync_getDifference")
	proto.RegisterType((*TLSyncGetChannelDifference)(nil), "mtproto.TL_sync_getChannelDifference")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RPCSyncClient is the client API for RPCSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RPCSyncClient interface {
	// sync.syncUpdates flags:# user_id:int auth_key_id:long server_id:flags.0?int not_me:flags.1?true updates:Updates = Bool;
	SyncSyncUpdates(ctx context.Context, in *TLSyncSyncUpdates, opts ...grpc.CallOption) (*Bool, error)
	// sync.pushUpdates user_id:int updates:Updates = Bool;
	SyncPushUpdates(ctx context.Context, in *TLSyncPushUpdates, opts ...grpc.CallOption) (*Bool, error)
	// sync.pushChannelUpdates channel_id:int exclude_user_id:int updates:Updates = Bool;
	SyncPushChannelUpdates(ctx context.Context, in *TLSyncPushChannelUpdates, opts ...grpc.CallOption) (*Bool, error)
	// sync.pushRpcResult server_id:int auth_key_id:long req_msg_id:long result:bytes = Bool;
	SyncPushRpcResult(ctx context.Context, in *TLSyncPushRpcResult, opts ...grpc.CallOption) (*Bool, error)
	// sync.getState auth_key_id:long user_id:int = updates.State;
	SyncGetState(ctx context.Context, in *TLSyncGetState, opts ...grpc.CallOption) (*Updates_State, error)
	// sync.getDifference flags:# auth_key_id:long user_id:int pts:int pts_total_limit:flags.0?int date:int qts:int = updates.Difference;
	SyncGetDifference(ctx context.Context, in *TLSyncGetDifference, opts ...grpc.CallOption) (*Updates_Difference, error)
	// sync.getChannelDifference flags:# auth_key_id:long user_id:int force:flags.0?true channel:InputChannel filter:ChannelMessagesFilter pts:int limit:int = updates.ChannelDifference;
	SyncGetChannelDifference(ctx context.Context, in *TLSyncGetChannelDifference, opts ...grpc.CallOption) (*Updates_ChannelDifference, error)
}

type rPCSyncClient struct {
	cc *grpc.ClientConn
}

func NewRPCSyncClient(cc *grpc.ClientConn) RPCSyncClient {
	return &rPCSyncClient{cc}
}

func (c *rPCSyncClient) SyncSyncUpdates(ctx context.Context, in *TLSyncSyncUpdates, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/mtproto.RPCSync/sync_syncUpdates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCSyncClient) SyncPushUpdates(ctx context.Context, in *TLSyncPushUpdates, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/mtproto.RPCSync/sync_pushUpdates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCSyncClient) SyncPushChannelUpdates(ctx context.Context, in *TLSyncPushChannelUpdates, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/mtproto.RPCSync/sync_pushChannelUpdates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCSyncClient) SyncPushRpcResult(ctx context.Context, in *TLSyncPushRpcResult, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/mtproto.RPCSync/sync_pushRpcResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCSyncClient) SyncGetState(ctx context.Context, in *TLSyncGetState, opts ...grpc.CallOption) (*Updates_State, error) {
	out := new(Updates_State)
	err := c.cc.Invoke(ctx, "/mtproto.RPCSync/sync_getState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCSyncClient) SyncGetDifference(ctx context.Context, in *TLSyncGetDifference, opts ...grpc.CallOption) (*Updates_Difference, error) {
	out := new(Updates_Difference)
	err := c.cc.Invoke(ctx, "/mtproto.RPCSync/sync_getDifference", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCSyncClient) SyncGetChannelDifference(ctx context.Context, in *TLSyncGetChannelDifference, opts ...grpc.CallOption) (*Updates_ChannelDifference, error) {
	out := new(Updates_ChannelDifference)
	err := c.cc.Invoke(ctx, "/mtproto.RPCSync/sync_getChannelDifference", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCSyncServer is the server API for RPCSync service.
type RPCSyncServer interface {
	// sync.syncUpdates flags:# user_id:int auth_key_id:long server_id:flags.0?int not_me:flags.1?true updates:Updates = Bool;
	SyncSyncUpdates(context.Context, *TLSyncSyncUpdates) (*Bool, error)
	// sync.pushUpdates user_id:int updates:Updates = Bool;
	SyncPushUpdates(context.Context, *TLSyncPushUpdates) (*Bool, error)
	// sync.pushChannelUpdates channel_id:int exclude_user_id:int updates:Updates = Bool;
	SyncPushChannelUpdates(context.Context, *TLSyncPushChannelUpdates) (*Bool, error)
	// sync.pushRpcResult server_id:int auth_key_id:long req_msg_id:long result:bytes = Bool;
	SyncPushRpcResult(context.Context, *TLSyncPushRpcResult) (*Bool, error)
	// sync.getState auth_key_id:long user_id:int = updates.State;
	SyncGetState(context.Context, *TLSyncGetState) (*Updates_State, error)
	// sync.getDifference flags:# auth_key_id:long user_id:int pts:int pts_total_limit:flags.0?int date:int qts:int = updates.Difference;
	SyncGetDifference(context.Context, *TLSyncGetDifference) (*Updates_Difference, error)
	// sync.getChannelDifference flags:# auth_key_id:long user_id:int force:flags.0?true channel:InputChannel filter:ChannelMessagesFilter pts:int limit:int = updates.ChannelDifference;
	SyncGetChannelDifference(context.Context, *TLSyncGetChannelDifference) (*Updates_ChannelDifference, error)
}

func RegisterRPCSyncServer(s *grpc.Server, srv RPCSyncServer) {
	s.RegisterService(&_RPCSync_serviceDesc, srv)
}

func _RPCSync_SyncSyncUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLSyncSyncUpdates)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCSyncServer).SyncSyncUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtproto.RPCSync/SyncSyncUpdates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCSyncServer).SyncSyncUpdates(ctx, req.(*TLSyncSyncUpdates))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCSync_SyncPushUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLSyncPushUpdates)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCSyncServer).SyncPushUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtproto.RPCSync/SyncPushUpdates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCSyncServer).SyncPushUpdates(ctx, req.(*TLSyncPushUpdates))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCSync_SyncPushChannelUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLSyncPushChannelUpdates)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCSyncServer).SyncPushChannelUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtproto.RPCSync/SyncPushChannelUpdates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCSyncServer).SyncPushChannelUpdates(ctx, req.(*TLSyncPushChannelUpdates))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCSync_SyncPushRpcResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLSyncPushRpcResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCSyncServer).SyncPushRpcResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtproto.RPCSync/SyncPushRpcResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCSyncServer).SyncPushRpcResult(ctx, req.(*TLSyncPushRpcResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCSync_SyncGetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLSyncGetState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCSyncServer).SyncGetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtproto.RPCSync/SyncGetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCSyncServer).SyncGetState(ctx, req.(*TLSyncGetState))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCSync_SyncGetDifference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLSyncGetDifference)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCSyncServer).SyncGetDifference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtproto.RPCSync/SyncGetDifference",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCSyncServer).SyncGetDifference(ctx, req.(*TLSyncGetDifference))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCSync_SyncGetChannelDifference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLSyncGetChannelDifference)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCSyncServer).SyncGetChannelDifference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtproto.RPCSync/SyncGetChannelDifference",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCSyncServer).SyncGetChannelDifference(ctx, req.(*TLSyncGetChannelDifference))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPCSync_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mtproto.RPCSync",
	HandlerType: (*RPCSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sync_syncUpdates",
			Handler:    _RPCSync_SyncSyncUpdates_Handler,
		},
		{
			MethodName: "sync_pushUpdates",
			Handler:    _RPCSync_SyncPushUpdates_Handler,
		},
		{
			MethodName: "sync_pushChannelUpdates",
			Handler:    _RPCSync_SyncPushChannelUpdates_Handler,
		},
		{
			MethodName: "sync_pushRpcResult",
			Handler:    _RPCSync_SyncPushRpcResult_Handler,
		},
		{
			MethodName: "sync_getState",
			Handler:    _RPCSync_SyncGetState_Handler,
		},
		{
			MethodName: "sync_getDifference",
			Handler:    _RPCSync_SyncGetDifference_Handler,
		},
		{
			MethodName: "sync_getChannelDifference",
			Handler:    _RPCSync_SyncGetChannelDifference_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.tl.proto",
}

func init() { proto.RegisterFile("service.tl.proto", fileDescriptor_service_tl_f5d2345e23df3c9b) }

var fileDescriptor_service_tl_f5d2345e23df3c9b = []byte{
	// 914 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x5d, 0x6f, 0xe3, 0x44,
	0x14, 0xad, 0x9b, 0xe6, 0xa3, 0xb7, 0x9b, 0x36, 0x3b, 0xa4, 0xdb, 0x34, 0xed, 0x96, 0xca, 0x7c,
	0x28, 0xac, 0x50, 0x90, 0x52, 0x09, 0xf1, 0xc0, 0x0b, 0x6d, 0xf9, 0x88, 0xb6, 0x85, 0xca, 0x4d,
	0x5f, 0x78, 0xb1, 0xbc, 0xe3, 0xdb, 0xc4, 0xc2, 0x19, 0xbb, 0x9e, 0xf1, 0x8a, 0xbc, 0xf1, 0xcc,
	0x0b, 0xff, 0x80, 0x5f, 0x80, 0x10, 0xbf, 0x10, 0x21, 0xcf, 0x8c, 0x63, 0x3b, 0x76, 0x15, 0x6d,
	0x81, 0x37, 0xfb, 0xdc, 0x3b, 0xe7, 0x9e, 0x39, 0xf7, 0x5e, 0x1b, 0x3a, 0x1c, 0xa3, 0xb7, 0x1e,
	0xc5, 0xa1, 0xf0, 0x87, 0x61, 0x14, 0x88, 0x80, 0x34, 0xe7, 0x42, 0x3e, 0xf4, 0xf7, 0x39, 0x9d,
	0xe1, 0xdc, 0x49, 0x22, 0x34, 0xa2, 0x67, 0x23, 0x15, 0xef, 0xf7, 0x73, 0x70, 0x10, 0xa1, 0x2d,
	0x16, 0x21, 0x72, 0x1d, 0xeb, 0x66, 0x31, 0xbe, 0x60, 0x54, 0xa1, 0xe6, 0x97, 0xd0, 0xbd, 0x08,
	0x18, 0x43, 0x2a, 0x26, 0xc1, 0x2d, 0x46, 0x6f, 0x31, 0xb2, 0x2f, 0x1d, 0xe1, 0x90, 0x0f, 0x61,
	0x37, 0xc9, 0xb2, 0xb9, 0xc2, 0x3c, 0xb7, 0x67, 0x9c, 0x1a, 0x83, 0xba, 0xf5, 0x2c, 0x41, 0x55,
	0xe2, 0xd8, 0x35, 0x7f, 0x31, 0x60, 0x6f, 0xe5, 0x38, 0xf9, 0x02, 0x76, 0x68, 0xc0, 0xb8, 0x88,
	0x62, 0x2a, 0x82, 0x48, 0x1e, 0xdb, 0x1d, 0xbd, 0x18, 0x6a, 0xe5, 0xc3, 0xc9, 0xd5, 0x45, 0x16,
	0xb5, 0xf2, 0xa9, 0xe4, 0x0c, 0xea, 0xae, 0x23, 0x9c, 0x51, 0x6f, 0xf3, 0xd4, 0x18, 0xec, 0x8c,
	0x5e, 0x2e, 0xcf, 0x54, 0x29, 0xb4, 0x54, 0xae, 0x79, 0x07, 0x27, 0x93, 0x2b, 0x5b, 0x6a, 0xa5,
	0x59, 0x1a, 0xe7, 0x5e, 0xc0, 0xb4, 0xa0, 0x27, 0xd1, 0x52, 0xe8, 0x2a, 0x54, 0x27, 0xa1, 0xab,
	0x7c, 0x79, 0x05, 0xcf, 0xb9, 0x62, 0x2f, 0x59, 0xb3, 0xc7, 0xf3, 0x65, 0xc7, 0x2e, 0x79, 0x1f,
	0x76, 0x74, 0x0e, 0x73, 0xe6, 0x28, 0xcb, 0x6f, 0x5b, 0xa0, 0xa0, 0xef, 0x9d, 0x39, 0x4a, 0xfb,
	0x56, 0xaa, 0xfc, 0x1f, 0xf6, 0x55, 0x5d, 0xa4, 0xc2, 0xbe, 0x82, 0xfc, 0x4c, 0xd0, 0x93, 0x68,
	0x7f, 0x37, 0xa0, 0x7d, 0x13, 0xf3, 0x59, 0x82, 0x29, 0xe3, 0x4e, 0x60, 0xc7, 0x89, 0xc5, 0xcc,
	0xfe, 0x09, 0x17, 0xa9, 0x65, 0x35, 0x6b, 0x3b, 0x81, 0x5e, 0xe3, 0x62, 0xec, 0x92, 0x57, 0xd0,
	0x8c, 0x43, 0xd7, 0x11, 0xc8, 0x75, 0xa1, 0xce, 0xb2, 0xd0, 0x9d, 0xc2, 0xad, 0x34, 0x81, 0x7c,
	0x02, 0xcf, 0xa9, 0xef, 0x21, 0x13, 0x76, 0x84, 0x0f, 0xf6, 0x9c, 0x4f, 0x13, 0xc6, 0x9a, 0x64,
	0xdc, 0x55, 0x01, 0x0b, 0x1f, 0xae, 0xf9, 0x74, 0xec, 0x92, 0x17, 0xd0, 0x88, 0x90, 0xc7, 0xbe,
	0xe8, 0x6d, 0x9d, 0x1a, 0x83, 0x67, 0x96, 0x7e, 0x33, 0x23, 0x68, 0xa5, 0xfa, 0xfe, 0x85, 0xe5,
	0x9f, 0x16, 0xbd, 0xc9, 0xce, 0x14, 0xee, 0x9e, 0x9a, 0xf2, 0x2d, 0x1c, 0xa4, 0x5e, 0x87, 0x31,
	0x9f, 0xe9, 0x6b, 0x49, 0x09, 0xef, 0x46, 0x34, 0x86, 0xc3, 0x3c, 0x91, 0x15, 0x52, 0x4b, 0xde,
	0xea, 0x09, 0x54, 0x7f, 0x1a, 0xf0, 0xde, 0x72, 0x00, 0x16, 0x8c, 0x6a, 0x51, 0xe4, 0x00, 0x9a,
	0x31, 0x57, 0xd3, 0xbd, 0x29, 0xa7, 0xbb, 0x91, 0xbc, 0x8e, 0xdd, 0xd5, 0x3e, 0xd6, 0x56, 0xfb,
	0x78, 0x04, 0xdb, 0xd9, 0x62, 0x6c, 0xc9, 0xa3, 0x2d, 0x9e, 0x6e, 0xc4, 0x3e, 0x34, 0x58, 0x20,
	0xec, 0x39, 0xf6, 0xea, 0xa7, 0xc6, 0xa0, 0x65, 0xd5, 0x59, 0x20, 0xae, 0x31, 0xdf, 0xfb, 0xc6,
	0x9a, 0xde, 0x9b, 0x3f, 0x66, 0x7a, 0x73, 0x26, 0xe6, 0xf5, 0x1a, 0x05, 0xbd, 0xef, 0x30, 0x57,
	0xe6, 0x6f, 0x06, 0xf4, 0xf3, 0xe4, 0x17, 0x33, 0x87, 0x31, 0xf4, 0xd3, 0x1a, 0x2f, 0x01, 0xa8,
	0x42, 0xb2, 0x32, 0xdb, 0x1a, 0x19, 0xbb, 0xe4, 0x63, 0xd8, 0xc3, 0x9f, 0xa9, 0x1f, 0xbb, 0x68,
	0x17, 0xad, 0x6b, 0x6b, 0xf8, 0xae, 0xa4, 0xa8, 0xb6, 0x4e, 0xd1, 0xaf, 0x06, 0xec, 0x57, 0xb6,
	0xba, 0xe8, 0xb3, 0xb1, 0xe2, 0xf3, 0x4a, 0x93, 0x36, 0x57, 0x9b, 0x74, 0x0c, 0x50, 0xda, 0x9c,
	0x56, 0xb4, 0x6e, 0x67, 0x5e, 0x43, 0x27, 0xd5, 0x32, 0x45, 0x71, 0x2b, 0x1c, 0x81, 0x6b, 0xd7,
	0xfa, 0xb1, 0x39, 0x32, 0xff, 0xca, 0xdd, 0x6c, 0x8a, 0xe2, 0xd2, 0xbb, 0xbf, 0xc7, 0x08, 0x19,
	0xc5, 0xb5, 0xe2, 0x73, 0x94, 0xb5, 0x42, 0xab, 0x3b, 0x50, 0x0b, 0x05, 0xd7, 0x43, 0x97, 0x3c,
	0x26, 0x2d, 0x09, 0x05, 0xb7, 0x45, 0x20, 0x1c, 0xdf, 0xf6, 0xbd, 0xb9, 0x27, 0xe4, 0xe0, 0xd5,
	0xad, 0x76, 0x28, 0xf8, 0x24, 0x41, 0xaf, 0x12, 0x90, 0x10, 0xd8, 0x4a, 0xfc, 0x96, 0xd3, 0x57,
	0xb7, 0xe4, 0x73, 0xc2, 0xf6, 0x20, 0x78, 0xaf, 0xa9, 0xd8, 0x1e, 0x04, 0x37, 0xff, 0x36, 0xe0,
	0x38, 0x27, 0x59, 0x4f, 0xc7, 0x7f, 0xa1, 0xbc, 0x0b, 0xf5, 0xfb, 0x20, 0xa2, 0x28, 0xb5, 0xb7,
	0x2c, 0xf5, 0x42, 0x3e, 0x83, 0xa6, 0x9e, 0x2e, 0xa9, 0x7a, 0x67, 0xb4, 0xbf, 0x1c, 0x94, 0x31,
	0x0b, 0xe3, 0x54, 0x80, 0x95, 0x66, 0x91, 0xcf, 0xa1, 0x71, 0xef, 0xf9, 0x02, 0x23, 0xbd, 0x46,
	0x27, 0xd9, 0xaf, 0x4e, 0x65, 0x5c, 0x23, 0xe7, 0xce, 0x14, 0xf9, 0x37, 0x32, 0xcb, 0xd2, 0xd9,
	0xa9, 0x71, 0xcd, 0xcc, 0xb8, 0x2e, 0xd4, 0x95, 0x5d, 0x2d, 0x89, 0xa9, 0x97, 0xd1, 0x1f, 0x5b,
	0xd0, 0xb4, 0x6e, 0x2e, 0x6e, 0x17, 0x8c, 0x92, 0xaf, 0xa0, 0x53, 0xfa, 0x68, 0x1c, 0xe7, 0xbe,
	0x99, 0xa5, 0x4f, 0x4a, 0xbf, 0xbd, 0x8c, 0x9e, 0x07, 0x81, 0x6f, 0x6e, 0x2c, 0x29, 0xf2, 0x7b,
	0x5c, 0xa6, 0xc8, 0x45, 0xcb, 0x14, 0x3f, 0xc0, 0xc1, 0x63, 0xdb, 0xfa, 0x41, 0x25, 0x53, 0x31,
	0xa9, 0x4c, 0xf8, 0x35, 0x90, 0x8a, 0x65, 0x3b, 0xa9, 0xe4, 0x5a, 0xc6, 0xcb, 0x34, 0x97, 0xd0,
	0x2e, 0xee, 0xc9, 0x61, 0x89, 0x21, 0x0d, 0xf5, 0xb3, 0x2f, 0xb4, 0xde, 0x7a, 0x5b, 0xe2, 0xe6,
	0x06, 0xb9, 0xd5, 0x62, 0x56, 0xf6, 0xa3, 0x8a, 0x2a, 0x8b, 0xf7, 0x8f, 0x4a, 0x7c, 0x59, 0xd0,
	0xdc, 0x20, 0x33, 0x38, 0x7c, 0x7c, 0x82, 0x3f, 0xaa, 0xe2, 0x2e, 0xa5, 0xf5, 0xcd, 0x52, 0x89,
	0x52, 0x8e, 0xb9, 0x71, 0x3e, 0x80, 0x23, 0x1a, 0xcc, 0x87, 0x0c, 0xdf, 0xc4, 0xbe, 0xe3, 0xcd,
	0x87, 0xc8, 0xa6, 0x1e, 0xc3, 0xf4, 0xe8, 0x79, 0xf3, 0x7a, 0x72, 0x93, 0x3c, 0x7c, 0xb7, 0xf9,
	0xa6, 0x21, 0x91, 0xb3, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x75, 0x55, 0xf3, 0x25, 0xf2, 0x0a,
	0x00, 0x00,
}
