// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nbfs_service.proto

/*
Package mtproto is a generated protocol buffer package.

It is generated from these files:
	nbfs_service.proto
	rpc_error_codes.proto
	schema.tl.core_types.proto
	schema.tl.crc32.proto
	schema.tl.handshake.proto
	schema.tl.handshake_service.proto
	schema.tl.sync.proto
	schema.tl.sync_service.proto
	schema.tl.transport.proto
	schema.tl.transport_service.proto
	zproto_auth_key.proto
	zproto_sync.proto

It has these top-level messages:
	UploadPhotoFileRequest
	GetPhotoFileDataRequest
	PhotoDataRsp
	Error_Data
	Error
	TLError
	Null_Data
	Null
	TLNull
	Bool_Data
	Bool
	TLBoolFalse
	TLBoolTrue
	True_Data
	True
	TLTrue
	Server_DHInnerData_Data
	Server_DHInnerData
	TLServer_DHInnerData
	Client_DH_Inner_Data_Data
	Client_DH_Inner_Data
	TLClient_DHInnerData
	SetClient_DHParamsAnswer_Data
	SetClient_DHParamsAnswer
	TLDhGenOk
	TLDhGenRetry
	TLDhGenFail
	DestroyAuthKeyRes_Data
	DestroyAuthKeyRes
	TLDestroyAuthKeyOk
	TLDestroyAuthKeyNone
	TLDestroyAuthKeyFail
	ResPQ_Data
	ResPQ
	TLResPQ
	P_QInnerData_Data
	P_QInnerData
	TLPQInnerData
	Server_DH_Params_Data
	Server_DH_Params
	TLServer_DHParamsFail
	TLServer_DHParamsOk
	TLReqPq
	TLReq_DHParams
	TLSetClient_DHParams
	TLDestroyAuthKey
	Messages_Messages_Data
	Messages_Messages
	TLMessagesMessages
	TLMessagesMessagesSlice
	TLMessagesChannelMessages
	ChannelMessagesFilter_Data
	ChannelMessagesFilter
	TLChannelMessagesFilterEmpty
	TLChannelMessagesFilter
	InputGame_Data
	InputGame
	TLInputGameID
	TLInputGameShortName
	ChannelBannedRights_Data
	ChannelBannedRights
	TLChannelBannedRights
	InputEncryptedFile_Data
	InputEncryptedFile
	TLInputEncryptedFileEmpty
	TLInputEncryptedFileUploaded
	TLInputEncryptedFile
	TLInputEncryptedFileBigUploaded
	NotifyPeer_Data
	NotifyPeer
	TLNotifyPeer
	TLNotifyUsers
	TLNotifyChats
	TLNotifyAll
	StickerSet_Data
	StickerSet
	TLStickerSet
	Messages_FeaturedStickers_Data
	Messages_FeaturedStickers
	TLMessagesFeaturedStickersNotModified
	TLMessagesFeaturedStickers
	PaymentRequestedInfo_Data
	PaymentRequestedInfo
	TLPaymentRequestedInfo
	LangPackString_Data
	LangPackString
	TLLangPackString
	TLLangPackStringPluralized
	TLLangPackStringDeleted
	ChatParticipants_Data
	ChatParticipants
	TLChatParticipantsForbidden
	TLChatParticipants
	Messages_AffectedHistory_Data
	Messages_AffectedHistory
	TLMessagesAffectedHistory
	PrivacyKey_Data
	PrivacyKey
	TLPrivacyKeyStatusTimestamp
	TLPrivacyKeyChatInvite
	TLPrivacyKeyPhoneCall
	Messages_Stickers_Data
	Messages_Stickers
	TLMessagesStickersNotModified
	TLMessagesStickers
	Messages_FoundGifs_Data
	Messages_FoundGifs
	TLMessagesFoundGifs
	DraftMessage_Data
	DraftMessage
	TLDraftMessageEmpty
	TLDraftMessage
	InputFile_Data
	InputFile
	TLInputFile
	TLInputFileBig
	InputMedia_Data
	InputMedia
	TLInputMediaEmpty
	TLInputMediaUploadedPhoto
	TLInputMediaPhoto
	TLInputMediaGeoPoint
	TLInputMediaContact
	TLInputMediaUploadedDocument
	TLInputMediaDocument
	TLInputMediaVenue
	TLInputMediaGifExternal
	TLInputMediaPhotoExternal
	TLInputMediaDocumentExternal
	TLInputMediaGame
	TLInputMediaInvoice
	User_Data
	User
	TLUserEmpty
	TLUser
	ChatPhoto_Data
	ChatPhoto
	TLChatPhotoEmpty
	TLChatPhoto
	PhotoSize_Data
	PhotoSize
	TLPhotoSizeEmpty
	TLPhotoSize
	TLPhotoCachedSize
	Contacts_Contacts_Data
	Contacts_Contacts
	TLContactsContactsNotModified
	TLContactsContacts
	Contacts_Blocked_Data
	Contacts_Blocked
	TLContactsBlocked
	TLContactsBlockedSlice
	Messages_HighScores_Data
	Messages_HighScores
	TLMessagesHighScores
	CdnPublicKey_Data
	CdnPublicKey
	TLCdnPublicKey
	LangPackDifference_Data
	LangPackDifference
	TLLangPackDifference
	ContactStatus_Data
	ContactStatus
	TLContactStatus
	FoundGif_Data
	FoundGif
	TLFoundGif
	TLFoundGifCached
	Messages_BotCallbackAnswer_Data
	Messages_BotCallbackAnswer
	TLMessagesBotCallbackAnswer
	TopPeerCategoryPeers_Data
	TopPeerCategoryPeers
	TLTopPeerCategoryPeers
	Messages_RecentStickers_Data
	Messages_RecentStickers
	TLMessagesRecentStickersNotModified
	TLMessagesRecentStickers
	PaymentSavedCredentials_Data
	PaymentSavedCredentials
	TLPaymentSavedCredentialsCard
	Account_TmpPassword_Data
	Account_TmpPassword
	TLAccountTmpPassword
	Messages_DhConfig_Data
	Messages_DhConfig
	TLMessagesDhConfigNotModified
	TLMessagesDhConfig
	Auth_SentCodeType_Data
	Auth_SentCodeType
	TLAuthSentCodeTypeApp
	TLAuthSentCodeTypeSms
	TLAuthSentCodeTypeCall
	TLAuthSentCodeTypeFlashCall
	Update_Data
	Update
	TLUpdateNewMessage
	TLUpdateMessageID
	TLUpdateDeleteMessages
	TLUpdateUserTyping
	TLUpdateChatUserTyping
	TLUpdateChatParticipants
	TLUpdateUserStatus
	TLUpdateUserName
	TLUpdateUserPhoto
	TLUpdateContactRegistered
	TLUpdateContactLink
	TLUpdateNewEncryptedMessage
	TLUpdateEncryptedChatTyping
	TLUpdateEncryption
	TLUpdateEncryptedMessagesRead
	TLUpdateChatParticipantAdd
	TLUpdateChatParticipantDelete
	TLUpdateDcOptions
	TLUpdateUserBlocked
	TLUpdateNotifySettings
	TLUpdateServiceNotification
	TLUpdatePrivacy
	TLUpdateUserPhone
	TLUpdateReadHistoryInbox
	TLUpdateReadHistoryOutbox
	TLUpdateWebPage
	TLUpdateReadMessagesContents
	TLUpdateChannelTooLong
	TLUpdateChannel
	TLUpdateNewChannelMessage
	TLUpdateReadChannelInbox
	TLUpdateDeleteChannelMessages
	TLUpdateChannelMessageViews
	TLUpdateChatAdmins
	TLUpdateChatParticipantAdmin
	TLUpdateNewStickerSet
	TLUpdateStickerSetsOrder
	TLUpdateStickerSets
	TLUpdateSavedGifs
	TLUpdateBotInlineQuery
	TLUpdateBotInlineSend
	TLUpdateEditChannelMessage
	TLUpdateChannelPinnedMessage
	TLUpdateBotCallbackQuery
	TLUpdateEditMessage
	TLUpdateInlineBotCallbackQuery
	TLUpdateReadChannelOutbox
	TLUpdateDraftMessage
	TLUpdateReadFeaturedStickers
	TLUpdateRecentStickers
	TLUpdateConfig
	TLUpdatePtsChanged
	TLUpdateChannelWebPage
	TLUpdateDialogPinned
	TLUpdatePinnedDialogs
	TLUpdateBotWebhookJSON
	TLUpdateBotWebhookJSONQuery
	TLUpdateBotShippingQuery
	TLUpdateBotPrecheckoutQuery
	TLUpdatePhoneCall
	TLUpdateLangPackTooLong
	TLUpdateLangPack
	TLUpdateFavedStickers
	TLUpdateChannelReadMessagesContents
	TLUpdateContactsReset
	InputBotInlineMessage_Data
	InputBotInlineMessage
	TLInputBotInlineMessageMediaAuto
	TLInputBotInlineMessageText
	TLInputBotInlineMessageMediaGeo
	TLInputBotInlineMessageMediaVenue
	TLInputBotInlineMessageMediaContact
	TLInputBotInlineMessageGame
	Contacts_TopPeers_Data
	Contacts_TopPeers
	TLContactsTopPeersNotModified
	TLContactsTopPeers
	MaskCoords_Data
	MaskCoords
	TLMaskCoords
	PhoneCallDiscardReason_Data
	PhoneCallDiscardReason
	TLPhoneCallDiscardReasonMissed
	TLPhoneCallDiscardReasonDisconnect
	TLPhoneCallDiscardReasonHangup
	TLPhoneCallDiscardReasonBusy
	ShippingOption_Data
	ShippingOption
	TLShippingOption
	ChannelAdminLogEvent_Data
	ChannelAdminLogEvent
	TLChannelAdminLogEvent
	InputChatPhoto_Data
	InputChatPhoto
	TLInputChatPhotoEmpty
	TLInputChatUploadedPhoto
	TLInputChatPhoto
	Contact_Data
	Contact
	TLContact
	Account_Password_Data
	Account_Password
	TLAccountNoPassword
	TLAccountPassword
	Messages_StickerSet_Data
	Messages_StickerSet
	TLMessagesStickerSet
	InputStickeredMedia_Data
	InputStickeredMedia
	TLInputStickeredMediaPhoto
	TLInputStickeredMediaDocument
	ChannelAdminLogEventAction_Data
	ChannelAdminLogEventAction
	TLChannelAdminLogEventActionChangeTitle
	TLChannelAdminLogEventActionChangeAbout
	TLChannelAdminLogEventActionChangeUsername
	TLChannelAdminLogEventActionChangePhoto
	TLChannelAdminLogEventActionToggleInvites
	TLChannelAdminLogEventActionToggleSignatures
	TLChannelAdminLogEventActionUpdatePinned
	TLChannelAdminLogEventActionEditMessage
	TLChannelAdminLogEventActionDeleteMessage
	TLChannelAdminLogEventActionParticipantJoin
	TLChannelAdminLogEventActionParticipantLeave
	TLChannelAdminLogEventActionParticipantInvite
	TLChannelAdminLogEventActionParticipantToggleBan
	TLChannelAdminLogEventActionParticipantToggleAdmin
	TLChannelAdminLogEventActionChangeStickerSet
	Chat_Data
	Chat
	TLChatEmpty
	TLChat
	TLChatForbidden
	TLChannel
	TLChannelForbidden
	MessageAction_Data
	MessageAction
	TLMessageActionEmpty
	TLMessageActionChatCreate
	TLMessageActionChatEditTitle
	TLMessageActionChatEditPhoto
	TLMessageActionChatDeletePhoto
	TLMessageActionChatAddUser
	TLMessageActionChatDeleteUser
	TLMessageActionChatJoinedByLink
	TLMessageActionChannelCreate
	TLMessageActionChatMigrateTo
	TLMessageActionChannelMigrateFrom
	TLMessageActionPinMessage
	TLMessageActionHistoryClear
	TLMessageActionGameScore
	TLMessageActionPaymentSentMe
	TLMessageActionPaymentSent
	TLMessageActionPhoneCall
	TLMessageActionScreenshotTaken
	ChannelParticipant_Data
	ChannelParticipant
	TLChannelParticipant
	TLChannelParticipantSelf
	TLChannelParticipantCreator
	TLChannelParticipantAdmin
	TLChannelParticipantBanned
	TopPeer_Data
	TopPeer
	TLTopPeer
	InputWebDocument_Data
	InputWebDocument
	TLInputWebDocument
	UserProfilePhoto_Data
	UserProfilePhoto
	TLUserProfilePhotoEmpty
	TLUserProfilePhoto
	UserFull_Data
	UserFull
	TLUserFull
	NearestDc_Data
	NearestDc
	TLNearestDc
	InputPrivacyRule_Data
	InputPrivacyRule
	TLInputPrivacyValueAllowContacts
	TLInputPrivacyValueAllowAll
	TLInputPrivacyValueAllowUsers
	TLInputPrivacyValueDisallowContacts
	TLInputPrivacyValueDisallowAll
	TLInputPrivacyValueDisallowUsers
	InputStickerSetItem_Data
	InputStickerSetItem
	TLInputStickerSetItem
	StickerSetCovered_Data
	StickerSetCovered
	TLStickerSetCovered
	TLStickerSetMultiCovered
	FileLocation_Data
	FileLocation
	TLFileLocationUnavailable
	TLFileLocation
	ChatParticipant_Data
	ChatParticipant
	TLChatParticipant
	TLChatParticipantCreator
	TLChatParticipantAdmin
	Auth_SentCode_Data
	Auth_SentCode
	TLAuthSentCode
	Contacts_Found_Data
	Contacts_Found
	TLContactsFound
	ReceivedNotifyMessage_Data
	ReceivedNotifyMessage
	TLReceivedNotifyMessage
	MessageEntity_Data
	MessageEntity
	TLMessageEntityUnknown
	TLMessageEntityMention
	TLMessageEntityHashtag
	TLMessageEntityBotCommand
	TLMessageEntityUrl
	TLMessageEntityEmail
	TLMessageEntityBold
	TLMessageEntityItalic
	TLMessageEntityCode
	TLMessageEntityPre
	TLMessageEntityTextUrl
	TLMessageEntityMentionName
	TLInputMessageEntityMentionName
	InputBotInlineResult_Data
	InputBotInlineResult
	TLInputBotInlineResult
	TLInputBotInlineResultPhoto
	TLInputBotInlineResultDocument
	TLInputBotInlineResultGame
	Photos_Photo_Data
	Photos_Photo
	TLPhotosPhoto
	Config_Data
	Config
	TLConfig
	KeyboardButton_Data
	KeyboardButton
	TLKeyboardButton
	TLKeyboardButtonUrl
	TLKeyboardButtonCallback
	TLKeyboardButtonRequestPhone
	TLKeyboardButtonRequestGeoLocation
	TLKeyboardButtonSwitchInline
	TLKeyboardButtonGame
	TLKeyboardButtonBuy
	Channels_ChannelParticipant_Data
	Channels_ChannelParticipant
	TLChannelsChannelParticipant
	InputWebFileLocation_Data
	InputWebFileLocation
	TLInputWebFileLocation
	PhoneCallProtocol_Data
	PhoneCallProtocol
	TLPhoneCallProtocol
	CdnFileHash_Data
	CdnFileHash
	TLCdnFileHash
	ChatInvite_Data
	ChatInvite
	TLChatInviteAlready
	TLChatInvite
	MessageMedia_Data
	MessageMedia
	TLMessageMediaEmpty
	TLMessageMediaPhoto
	TLMessageMediaGeo
	TLMessageMediaContact
	TLMessageMediaUnsupported
	TLMessageMediaDocument
	TLMessageMediaWebPage
	TLMessageMediaVenue
	TLMessageMediaGame
	TLMessageMediaInvoice
	InputPeerNotifyEvents_Data
	InputPeerNotifyEvents
	TLInputPeerNotifyEventsEmpty
	TLInputPeerNotifyEventsAll
	PeerNotifySettings_Data
	PeerNotifySettings
	TLPeerNotifySettingsEmpty
	TLPeerNotifySettings
	Contacts_Link_Data
	Contacts_Link
	TLContactsLink
	Updates_Difference_Data
	Updates_Difference
	TLUpdatesDifferenceEmpty
	TLUpdatesDifference
	TLUpdatesDifferenceSlice
	TLUpdatesDifferenceTooLong
	Help_InviteText_Data
	Help_InviteText
	TLHelpInviteText
	SendMessageAction_Data
	SendMessageAction
	TLSendMessageTypingAction
	TLSendMessageCancelAction
	TLSendMessageRecordVideoAction
	TLSendMessageUploadVideoAction
	TLSendMessageRecordAudioAction
	TLSendMessageUploadAudioAction
	TLSendMessageUploadPhotoAction
	TLSendMessageUploadDocumentAction
	TLSendMessageGeoLocationAction
	TLSendMessageChooseContactAction
	TLSendMessageGamePlayAction
	TLSendMessageRecordRoundAction
	TLSendMessageUploadRoundAction
	InputChannel_Data
	InputChannel
	TLInputChannelEmpty
	TLInputChannel
	Messages_MessageEditData_Data
	Messages_MessageEditData
	TLMessagesMessageEditData
	PhoneCall_Data
	PhoneCall
	TLPhoneCallEmpty
	TLPhoneCallWaiting
	TLPhoneCallRequested
	TLPhoneCallAccepted
	TLPhoneCall
	TLPhoneCallDiscarded
	PostAddress_Data
	PostAddress
	TLPostAddress
	InputFileLocation_Data
	InputFileLocation
	TLInputFileLocation
	TLInputEncryptedFileLocation
	TLInputDocumentFileLocation
	Peer_Data
	Peer
	TLPeerUser
	TLPeerChat
	TLPeerChannel
	InputNotifyPeer_Data
	InputNotifyPeer
	TLInputNotifyPeer
	TLInputNotifyUsers
	TLInputNotifyChats
	TLInputNotifyAll
	BotCommand_Data
	BotCommand
	TLBotCommand
	BotInlineMessage_Data
	BotInlineMessage
	TLBotInlineMessageMediaAuto
	TLBotInlineMessageText
	TLBotInlineMessageMediaGeo
	TLBotInlineMessageMediaVenue
	TLBotInlineMessageMediaContact
	Messages_StickerSetInstallResult_Data
	Messages_StickerSetInstallResult
	TLMessagesStickerSetInstallResultSuccess
	TLMessagesStickerSetInstallResultArchive
	LabeledPrice_Data
	LabeledPrice
	TLLabeledPrice
	InputPeer_Data
	InputPeer
	TLInputPeerEmpty
	TLInputPeerSelf
	TLInputPeerChat
	TLInputPeerUser
	TLInputPeerChannel
	Photo_Data
	Photo
	TLPhotoEmpty
	TLPhoto
	ContactBlocked_Data
	ContactBlocked
	TLContactBlocked
	DcOption_Data
	DcOption
	TLDcOption
	Messages_SentEncryptedMessage_Data
	Messages_SentEncryptedMessage
	TLMessagesSentEncryptedMessage
	TLMessagesSentEncryptedFile
	Account_PasswordSettings_Data
	Account_PasswordSettings
	TLAccountPasswordSettings
	Messages_BotResults_Data
	Messages_BotResults
	TLMessagesBotResults
	DataJSON_Data
	DataJSON
	TLDataJSON
	Payments_ValidatedRequestedInfo_Data
	Payments_ValidatedRequestedInfo
	TLPaymentsValidatedRequestedInfo
	Payments_PaymentReceipt_Data
	Payments_PaymentReceipt
	TLPaymentsPaymentReceipt
	InputEncryptedChat_Data
	InputEncryptedChat
	TLInputEncryptedChat
	BotInfo_Data
	BotInfo
	TLBotInfo
	Invoice_Data
	Invoice
	TLInvoice
	InputPhoneCall_Data
	InputPhoneCall
	TLInputPhoneCall
	Auth_Authorization_Data
	Auth_Authorization
	TLAuthAuthorization
	Photos_Photos_Data
	Photos_Photos
	TLPhotosPhotos
	TLPhotosPhotosSlice
	DisabledFeature_Data
	DisabledFeature
	TLDisabledFeature
	InlineBotSwitchPM_Data
	InlineBotSwitchPM
	TLInlineBotSwitchPM
	Payments_PaymentResult_Data
	Payments_PaymentResult
	TLPaymentsPaymentResult
	TLPaymentsPaymentVerficationNeeded
	ChannelAdminLogEventsFilter_Data
	ChannelAdminLogEventsFilter
	TLChannelAdminLogEventsFilter
	InputContact_Data
	InputContact
	TLInputPhoneContact
	Messages_Chats_Data
	Messages_Chats
	TLMessagesChats
	TLMessagesChatsSlice
	InputPrivacyKey_Data
	InputPrivacyKey
	TLInputPrivacyKeyStatusTimestamp
	TLInputPrivacyKeyChatInvite
	TLInputPrivacyKeyPhoneCall
	Messages_AffectedMessages_Data
	Messages_AffectedMessages
	TLMessagesAffectedMessages
	Messages_SavedGifs_Data
	Messages_SavedGifs
	TLMessagesSavedGifsNotModified
	TLMessagesSavedGifs
	Messages_ArchivedStickers_Data
	Messages_ArchivedStickers
	TLMessagesArchivedStickers
	ChannelParticipantsFilter_Data
	ChannelParticipantsFilter
	TLChannelParticipantsRecent
	TLChannelParticipantsAdmins
	TLChannelParticipantsKicked
	TLChannelParticipantsBots
	TLChannelParticipantsBanned
	TLChannelParticipantsSearch
	PeerSettings_Data
	PeerSettings
	TLPeerSettings
	Game_Data
	Game
	TLGame
	InputAppEvent_Data
	InputAppEvent
	TLInputAppEvent
	Messages_Dialogs_Data
	Messages_Dialogs
	TLMessagesDialogs
	TLMessagesDialogsSlice
	AccountDaysTTL_Data
	AccountDaysTTL
	TLAccountDaysTTL
	Account_Authorizations_Data
	Account_Authorizations
	TLAccountAuthorizations
	ReplyMarkup_Data
	ReplyMarkup
	TLReplyKeyboardHide
	TLReplyKeyboardForceReply
	TLReplyKeyboardMarkup
	TLReplyInlineMarkup
	BotInlineResult_Data
	BotInlineResult
	TLBotInlineResult
	TLBotInlineMediaResult
	MessageFwdHeader_Data
	MessageFwdHeader
	TLMessageFwdHeader
	Page_Data
	Page
	TLPagePart
	TLPageFull
	Messages_FavedStickers_Data
	Messages_FavedStickers
	TLMessagesFavedStickersNotModified
	TLMessagesFavedStickers
	InputBotInlineMessageID_Data
	InputBotInlineMessageID
	TLInputBotInlineMessageID
	Storage_FileType_Data
	Storage_FileType
	TLStorageFileUnknown
	TLStorageFilePartial
	TLStorageFileJpeg
	TLStorageFileGif
	TLStorageFilePng
	TLStorageFilePdf
	TLStorageFileMp3
	TLStorageFileMov
	TLStorageFileMp4
	TLStorageFileWebp
	MessagesFilter_Data
	MessagesFilter
	TLInputMessagesFilterEmpty
	TLInputMessagesFilterPhotos
	TLInputMessagesFilterVideo
	TLInputMessagesFilterPhotoVideo
	TLInputMessagesFilterPhotoVideoDocuments
	TLInputMessagesFilterDocument
	TLInputMessagesFilterUrl
	TLInputMessagesFilterGif
	TLInputMessagesFilterVoice
	TLInputMessagesFilterMusic
	TLInputMessagesFilterChatPhotos
	TLInputMessagesFilterPhoneCalls
	TLInputMessagesFilterRoundVoice
	TLInputMessagesFilterRoundVideo
	TLInputMessagesFilterMyMentions
	EncryptedChat_Data
	EncryptedChat
	TLEncryptedChatEmpty
	TLEncryptedChatWaiting
	TLEncryptedChatRequested
	TLEncryptedChat
	TLEncryptedChatDiscarded
	EncryptedFile_Data
	EncryptedFile
	TLEncryptedFileEmpty
	TLEncryptedFile
	EncryptedMessage_Data
	EncryptedMessage
	TLEncryptedMessage
	TLEncryptedMessageService
	PrivacyRule_Data
	PrivacyRule
	TLPrivacyValueAllowContacts
	TLPrivacyValueAllowAll
	TLPrivacyValueAllowUsers
	TLPrivacyValueDisallowContacts
	TLPrivacyValueDisallowAll
	TLPrivacyValueDisallowUsers
	Updates_ChannelDifference_Data
	Updates_ChannelDifference
	TLUpdatesChannelDifferenceEmpty
	TLUpdatesChannelDifferenceTooLong
	TLUpdatesChannelDifference
	CdnConfig_Data
	CdnConfig
	TLCdnConfig
	PopularContact_Data
	PopularContact
	TLPopularContact
	Contacts_ResolvedPeer_Data
	Contacts_ResolvedPeer
	TLContactsResolvedPeer
	GeoPoint_Data
	GeoPoint
	TLGeoPointEmpty
	TLGeoPoint
	Auth_CheckedPhone_Data
	Auth_CheckedPhone
	TLAuthCheckedPhone
	Auth_ExportedAuthorization_Data
	Auth_ExportedAuthorization
	TLAuthExportedAuthorization
	Contacts_ImportedContacts_Data
	Contacts_ImportedContacts
	TLContactsImportedContacts
	Updates_Data
	Updates
	TLUpdatesTooLong
	TLUpdateShortMessage
	TLUpdateShortChatMessage
	TLUpdateShort
	TLUpdatesCombined
	TLUpdates
	TLUpdateShortSentMessage
	StickerPack_Data
	StickerPack
	TLStickerPack
	Messages_AllStickers_Data
	Messages_AllStickers
	TLMessagesAllStickersNotModified
	TLMessagesAllStickers
	Channels_ChannelParticipants_Data
	Channels_ChannelParticipants
	TLChannelsChannelParticipants
	ChatFull_Data
	ChatFull
	TLChatFull
	TLChannelFull
	Dialog_Data
	Dialog
	TLDialog
	Updates_State_Data
	Updates_State
	TLUpdatesState
	Help_AppUpdate_Data
	Help_AppUpdate
	TLHelpAppUpdate
	TLHelpNoAppUpdate
	InputStickerSet_Data
	InputStickerSet
	TLInputStickerSetEmpty
	TLInputStickerSetID
	TLInputStickerSetShortName
	Help_TermsOfService_Data
	Help_TermsOfService
	TLHelpTermsOfService
	Auth_CodeType_Data
	Auth_CodeType
	TLAuthCodeTypeSms
	TLAuthCodeTypeCall
	TLAuthCodeTypeFlashCall
	Message_Data
	Message
	TLMessageEmpty
	TLMessage
	TLMessageService
	InputPeerNotifySettings_Data
	InputPeerNotifySettings
	TLInputPeerNotifySettings
	ReportReason_Data
	ReportReason
	TLInputReportReasonSpam
	TLInputReportReasonViolence
	TLInputReportReasonPornography
	TLInputReportReasonOther
	Upload_File_Data
	Upload_File
	TLUploadFile
	TLUploadFileCdnRedirect
	Upload_WebFile_Data
	Upload_WebFile
	TLUploadWebFile
	Upload_CdnFile_Data
	Upload_CdnFile
	TLUploadCdnFileReuploadNeeded
	TLUploadCdnFile
	PaymentCharge_Data
	PaymentCharge
	TLPaymentCharge
	InputUser_Data
	InputUser
	TLInputUserEmpty
	TLInputUserSelf
	TLInputUser
	InputGeoPoint_Data
	InputGeoPoint
	TLInputGeoPointEmpty
	TLInputGeoPoint
	InputDocument_Data
	InputDocument
	TLInputDocumentEmpty
	TLInputDocument
	DocumentAttribute_Data
	DocumentAttribute
	TLDocumentAttributeImageSize
	TLDocumentAttributeAnimated
	TLDocumentAttributeSticker
	TLDocumentAttributeVideo
	TLDocumentAttributeAudio
	TLDocumentAttributeFilename
	TLDocumentAttributeHasStickers
	Authorization_Data
	Authorization
	TLAuthorization
	KeyboardButtonRow_Data
	KeyboardButtonRow
	TLKeyboardButtonRow
	RichText_Data
	RichText
	TLTextEmpty
	TLTextPlain
	TLTextBold
	TLTextItalic
	TLTextUnderline
	TLTextStrike
	TLTextFixed
	TLTextUrl
	TLTextEmail
	TLTextConcat
	Payments_SavedInfo_Data
	Payments_SavedInfo
	TLPaymentsSavedInfo
	Channels_AdminLogResults_Data
	Channels_AdminLogResults
	TLChannelsAdminLogResults
	Messages_ChatFull_Data
	Messages_ChatFull
	TLMessagesChatFull
	Document_Data
	Document
	TLDocumentEmpty
	TLDocument
	Help_Support_Data
	Help_Support
	TLHelpSupport
	WebPage_Data
	WebPage
	TLWebPageEmpty
	TLWebPagePending
	TLWebPage
	TLWebPageNotModified
	Auth_PasswordRecovery_Data
	Auth_PasswordRecovery
	TLAuthPasswordRecovery
	WebDocument_Data
	WebDocument
	TLWebDocument
	Phone_PhoneCall_Data
	Phone_PhoneCall
	TLPhonePhoneCall
	InputPhoto_Data
	InputPhoto
	TLInputPhotoEmpty
	TLInputPhoto
	UserStatus_Data
	UserStatus
	TLUserStatusEmpty
	TLUserStatusOnline
	TLUserStatusOffline
	TLUserStatusRecently
	TLUserStatusLastWeek
	TLUserStatusLastMonth
	Account_PasswordInputSettings_Data
	Account_PasswordInputSettings
	TLAccountPasswordInputSettings
	ExportedChatInvite_Data
	ExportedChatInvite
	TLChatInviteEmpty
	TLChatInviteExported
	HighScore_Data
	HighScore
	TLHighScore
	PageBlock_Data
	PageBlock
	TLPageBlockUnsupported
	TLPageBlockTitle
	TLPageBlockSubtitle
	TLPageBlockAuthorDate
	TLPageBlockHeader
	TLPageBlockSubheader
	TLPageBlockParagraph
	TLPageBlockPreformatted
	TLPageBlockFooter
	TLPageBlockDivider
	TLPageBlockAnchor
	TLPageBlockList
	TLPageBlockBlockquote
	TLPageBlockPullquote
	TLPageBlockPhoto
	TLPageBlockVideo
	TLPageBlockCover
	TLPageBlockEmbed
	TLPageBlockEmbedPost
	TLPageBlockCollage
	TLPageBlockSlideshow
	TLPageBlockChannel
	TLPageBlockAudio
	InputPaymentCredentials_Data
	InputPaymentCredentials
	TLInputPaymentCredentialsSaved
	TLInputPaymentCredentials
	LangPackLanguage_Data
	LangPackLanguage
	TLLangPackLanguage
	WallPaper_Data
	WallPaper
	TLWallPaper
	TLWallPaperSolid
	TopPeerCategory_Data
	TopPeerCategory
	TLTopPeerCategoryBotsPM
	TLTopPeerCategoryBotsInline
	TLTopPeerCategoryCorrespondents
	TLTopPeerCategoryGroups
	TLTopPeerCategoryChannels
	TLTopPeerCategoryPhoneCalls
	ImportedContact_Data
	ImportedContact
	TLImportedContact
	MessageRange_Data
	MessageRange
	TLMessageRange
	ExportedMessageLink_Data
	ExportedMessageLink
	TLExportedMessageLink
	Messages_PeerDialogs_Data
	Messages_PeerDialogs
	TLMessagesPeerDialogs
	Payments_PaymentForm_Data
	Payments_PaymentForm
	TLPaymentsPaymentForm
	PeerNotifyEvents_Data
	PeerNotifyEvents
	TLPeerNotifyEventsEmpty
	TLPeerNotifyEventsAll
	Account_PrivacyRules_Data
	Account_PrivacyRules
	TLAccountPrivacyRules
	ContactLink_Data
	ContactLink
	TLContactLinkUnknown
	TLContactLinkNone
	TLContactLinkHasPhone
	TLContactLinkContact
	PhoneConnection_Data
	PhoneConnection
	TLPhoneConnection
	ChannelAdminRights_Data
	ChannelAdminRights
	TLChannelAdminRights
	TLInvokeAfterMsg
	TLInvokeAfterMsgs
	TLInitConnection
	TLInvokeWithLayer
	TLInvokeWithoutUpdates
	TLAuthCheckPhone
	TLAuthSendCode
	TLAuthSignUp
	TLAuthSignIn
	TLAuthLogOut
	TLAuthResetAuthorizations
	TLAuthSendInvites
	TLAuthExportAuthorization
	TLAuthImportAuthorization
	TLAuthBindTempAuthKey
	TLAuthImportBotAuthorization
	TLAuthCheckPassword
	TLAuthRequestPasswordRecovery
	TLAuthRecoverPassword
	TLAuthResendCode
	TLAuthCancelCode
	TLAuthDropTempAuthKeys
	TLAccountRegisterDevice
	TLAccountUnregisterDevice
	TLAccountUpdateNotifySettings
	TLAccountGetNotifySettings
	TLAccountResetNotifySettings
	TLAccountUpdateProfile
	TLAccountUpdateStatus
	TLAccountGetWallPapers
	TLAccountReportPeer
	TLAccountCheckUsername
	TLAccountUpdateUsername
	TLAccountGetPrivacy
	TLAccountSetPrivacy
	TLAccountDeleteAccount
	TLAccountGetAccountTTL
	TLAccountSetAccountTTL
	TLAccountSendChangePhoneCode
	TLAccountChangePhone
	TLAccountUpdateDeviceLocked
	TLAccountGetAuthorizations
	TLAccountResetAuthorization
	TLAccountGetPassword
	TLAccountGetPasswordSettings
	TLAccountUpdatePasswordSettings
	TLAccountSendConfirmPhoneCode
	TLAccountConfirmPhone
	TLAccountGetTmpPassword
	TLUsersGetUsers
	TLUsersGetFullUser
	TLContactsGetStatuses
	TLContactsGetContacts
	TLContactsGetContactsLayer70
	TLContactsImportContacts
	TLContactsDeleteContact
	TLContactsDeleteContacts
	TLContactsBlock
	TLContactsUnblock
	TLContactsGetBlocked
	TLContactsExportCard
	TLContactsImportCard
	TLContactsSearch
	TLContactsResolveUsername
	TLContactsGetTopPeers
	TLContactsResetTopPeerRating
	TLContactsResetSaved
	TLMessagesGetMessages
	TLMessagesGetDialogs
	TLMessagesGetHistory
	TLMessagesSearch
	TLMessagesReadHistory
	TLMessagesDeleteHistory
	TLMessagesDeleteMessages
	TLMessagesReceivedMessages
	TLMessagesSetTyping
	TLMessagesSendMessage
	TLMessagesSendMedia
	TLMessagesForwardMessages
	TLMessagesReportSpam
	TLMessagesHideReportSpam
	TLMessagesGetPeerSettings
	TLMessagesGetChats
	TLMessagesGetFullChat
	TLMessagesEditChatTitle
	TLMessagesEditChatPhoto
	TLMessagesAddChatUser
	TLMessagesDeleteChatUser
	TLMessagesCreateChat
	TLMessagesForwardMessage
	TLMessagesGetDhConfig
	TLMessagesRequestEncryption
	TLMessagesAcceptEncryption
	TLMessagesDiscardEncryption
	TLMessagesSetEncryptedTyping
	TLMessagesReadEncryptedHistory
	TLMessagesSendEncrypted
	TLMessagesSendEncryptedFile
	TLMessagesSendEncryptedService
	TLMessagesReceivedQueue
	TLMessagesReportEncryptedSpam
	TLMessagesReadMessageContents
	TLMessagesGetAllStickers
	TLMessagesGetWebPagePreview
	TLMessagesExportChatInvite
	TLMessagesCheckChatInvite
	TLMessagesImportChatInvite
	TLMessagesGetStickerSet
	TLMessagesInstallStickerSet
	TLMessagesUninstallStickerSet
	TLMessagesStartBot
	TLMessagesGetMessagesViews
	TLMessagesToggleChatAdmins
	TLMessagesEditChatAdmin
	TLMessagesMigrateChat
	TLMessagesSearchGlobal
	TLMessagesReorderStickerSets
	TLMessagesGetDocumentByHash
	TLMessagesSearchGifs
	TLMessagesGetSavedGifs
	TLMessagesSaveGif
	TLMessagesGetInlineBotResults
	TLMessagesSetInlineBotResults
	TLMessagesSendInlineBotResult
	TLMessagesGetMessageEditData
	TLMessagesEditMessage
	TLMessagesEditInlineBotMessage
	TLMessagesGetBotCallbackAnswer
	TLMessagesSetBotCallbackAnswer
	TLMessagesGetPeerDialogs
	TLMessagesSaveDraft
	TLMessagesGetAllDrafts
	TLMessagesGetFeaturedStickers
	TLMessagesReadFeaturedStickers
	TLMessagesGetRecentStickers
	TLMessagesSaveRecentSticker
	TLMessagesClearRecentStickers
	TLMessagesGetArchivedStickers
	TLMessagesGetMaskStickers
	TLMessagesGetAttachedStickers
	TLMessagesSetGameScore
	TLMessagesSetInlineGameScore
	TLMessagesGetGameHighScores
	TLMessagesGetInlineGameHighScores
	TLMessagesGetCommonChats
	TLMessagesGetAllChats
	TLMessagesGetWebPage
	TLMessagesToggleDialogPin
	TLMessagesReorderPinnedDialogs
	TLMessagesGetPinnedDialogs
	TLMessagesSetBotShippingResults
	TLMessagesSetBotPrecheckoutResults
	TLMessagesUploadMedia
	TLMessagesSendScreenshotNotification
	TLMessagesGetFavedStickers
	TLMessagesFaveSticker
	TLMessagesGetUnreadMentions
	TLUpdatesGetState
	TLUpdatesGetDifference
	TLUpdatesGetChannelDifference
	TLPhotosUpdateProfilePhoto
	TLPhotosUploadProfilePhoto
	TLPhotosDeletePhotos
	TLPhotosGetUserPhotos
	TLUploadSaveFilePart
	TLUploadGetFile
	TLUploadSaveBigFilePart
	TLUploadGetWebFile
	TLUploadGetCdnFile
	TLUploadReuploadCdnFile
	TLUploadGetCdnFileHashes
	TLHelpGetConfig
	TLHelpGetNearestDc
	TLHelpGetAppUpdate
	TLHelpSaveAppLog
	TLHelpGetInviteText
	TLHelpGetSupport
	TLHelpGetAppChangelog
	TLHelpGetTermsOfService
	TLHelpSetBotUpdatesStatus
	TLHelpGetCdnConfig
	TLChannelsReadHistory
	TLChannelsDeleteMessages
	TLChannelsDeleteUserHistory
	TLChannelsReportSpam
	TLChannelsGetMessages
	TLChannelsGetParticipants
	TLChannelsGetParticipant
	TLChannelsGetChannels
	TLChannelsGetFullChannel
	TLChannelsCreateChannel
	TLChannelsEditAbout
	TLChannelsEditAdmin
	TLChannelsEditTitle
	TLChannelsEditPhoto
	TLChannelsCheckUsername
	TLChannelsUpdateUsername
	TLChannelsJoinChannel
	TLChannelsLeaveChannel
	TLChannelsInviteToChannel
	TLChannelsExportInvite
	TLChannelsDeleteChannel
	TLChannelsToggleInvites
	TLChannelsExportMessageLink
	TLChannelsToggleSignatures
	TLChannelsUpdatePinnedMessage
	TLChannelsGetAdminedPublicChannels
	TLChannelsEditBanned
	TLChannelsGetAdminLog
	TLChannelsSetStickers
	TLChannelsReadMessageContents
	TLBotsSendCustomRequest
	TLBotsAnswerWebhookJSONQuery
	TLPaymentsGetPaymentForm
	TLPaymentsGetPaymentReceipt
	TLPaymentsValidateRequestedInfo
	TLPaymentsSendPaymentForm
	TLPaymentsGetSavedInfo
	TLPaymentsClearSavedInfo
	TLStickersCreateStickerSet
	TLStickersRemoveStickerFromSet
	TLStickersChangeStickerPosition
	TLStickersAddStickerToSet
	TLPhoneGetCallConfig
	TLPhoneRequestCall
	TLPhoneAcceptCall
	TLPhoneConfirmCall
	TLPhoneReceivedCall
	TLPhoneDiscardCall
	TLPhoneSetCallRating
	TLPhoneSaveCallDebug
	TLLangpackGetLangPack
	TLLangpackGetStrings
	TLLangpackGetDifference
	TLLangpackGetLanguages
	Vector_WallPaper
	Vector_User
	Vector_ContactStatus
	VectorInt
	Vector_ReceivedNotifyMessage
	VectorLong
	Vector_StickerSetCovered
	Vector_CdnFileHash
	Vector_LangPackString
	Vector_LangPackLanguage
	FutureSalt_Data
	FutureSalt
	TLFutureSalt
	Pong_Data
	Pong
	TLPong
	DestroySessionRes_Data
	DestroySessionRes
	TLDestroySessionOk
	TLDestroySessionNone
	NewSession_Data
	NewSession
	TLNewSessionCreated
	Help_ConfigSimple_Data
	Help_ConfigSimple
	TLHelpConfigSimple
	MsgsStateReq_Data
	MsgsStateReq
	TLMsgsStateReq
	MsgsAllInfo_Data
	MsgsAllInfo
	TLMsgsAllInfo
	MsgResendReq_Data
	MsgResendReq
	TLMsgResendReq
	RpcDropAnswer_Data
	RpcDropAnswer
	TLRpcAnswerUnknown
	TLRpcAnswerDroppedRunning
	TLRpcAnswerDropped
	BadMsgNotification_Data
	BadMsgNotification
	TLBadMsgNotification
	TLBadServerSalt
	MsgsStateInfo_Data
	MsgsStateInfo
	TLMsgsStateInfo
	MsgDetailedInfo_Data
	MsgDetailedInfo
	TLMsgDetailedInfo
	TLMsgNewDetailedInfo
	RpcError_Data
	RpcError
	TLRpcError
	HttpWait_Data
	HttpWait
	TLHttpWait
	IpPort_Data
	IpPort
	TLIpPort
	MsgsAck_Data
	MsgsAck
	TLMsgsAck
	FutureSalts_Data
	FutureSalts
	TLFutureSalts
	TLRpcDropAnswer
	TLGetFutureSalts
	TLPing
	TLPingDelayDisconnect
	TLDestroySession
	TLContestSaveDeveloperInfo
	AuthKeyMetadata
	VoidRsp
	ClientUpdatesState
	ConnectToSessionServerReq
	SessionServerConnectedRsp
	PushUpdatesData
	UpdatesRequest
*/
package mtproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UploadPhotoFileRequest struct {
	OwnerId int64      `protobuf:"varint,1,opt,name=ownerId" json:"ownerId,omitempty"`
	File    *InputFile `protobuf:"bytes,2,opt,name=file" json:"file,omitempty"`
}

func (m *UploadPhotoFileRequest) Reset()                    { *m = UploadPhotoFileRequest{} }
func (m *UploadPhotoFileRequest) String() string            { return proto.CompactTextString(m) }
func (*UploadPhotoFileRequest) ProtoMessage()               {}
func (*UploadPhotoFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UploadPhotoFileRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *UploadPhotoFileRequest) GetFile() *InputFile {
	if m != nil {
		return m.File
	}
	return nil
}

type GetPhotoFileDataRequest struct {
	PhotoId int64 `protobuf:"varint,1,opt,name=photo_id,json=photoId" json:"photo_id,omitempty"`
}

func (m *GetPhotoFileDataRequest) Reset()                    { *m = GetPhotoFileDataRequest{} }
func (m *GetPhotoFileDataRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPhotoFileDataRequest) ProtoMessage()               {}
func (*GetPhotoFileDataRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetPhotoFileDataRequest) GetPhotoId() int64 {
	if m != nil {
		return m.PhotoId
	}
	return 0
}

type PhotoDataRsp struct {
	PhotoId  int64        `protobuf:"varint,1,opt,name=photo_id,json=photoId" json:"photo_id,omitempty"`
	SizeList []*PhotoSize `protobuf:"bytes,2,rep,name=size_list,json=sizeList" json:"size_list,omitempty"`
}

func (m *PhotoDataRsp) Reset()                    { *m = PhotoDataRsp{} }
func (m *PhotoDataRsp) String() string            { return proto.CompactTextString(m) }
func (*PhotoDataRsp) ProtoMessage()               {}
func (*PhotoDataRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PhotoDataRsp) GetPhotoId() int64 {
	if m != nil {
		return m.PhotoId
	}
	return 0
}

func (m *PhotoDataRsp) GetSizeList() []*PhotoSize {
	if m != nil {
		return m.SizeList
	}
	return nil
}

func init() {
	proto.RegisterType((*UploadPhotoFileRequest)(nil), "mtproto.UploadPhotoFileRequest")
	proto.RegisterType((*GetPhotoFileDataRequest)(nil), "mtproto.GetPhotoFileDataRequest")
	proto.RegisterType((*PhotoDataRsp)(nil), "mtproto.PhotoDataRsp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RPCNbfs service

type RPCNbfsClient interface {
	NbfsUploadPhotoFile(ctx context.Context, in *UploadPhotoFileRequest, opts ...grpc.CallOption) (*PhotoDataRsp, error)
	NbfsGetPhotoFileData(ctx context.Context, in *GetPhotoFileDataRequest, opts ...grpc.CallOption) (*PhotoDataRsp, error)
}

type rPCNbfsClient struct {
	cc *grpc.ClientConn
}

func NewRPCNbfsClient(cc *grpc.ClientConn) RPCNbfsClient {
	return &rPCNbfsClient{cc}
}

func (c *rPCNbfsClient) NbfsUploadPhotoFile(ctx context.Context, in *UploadPhotoFileRequest, opts ...grpc.CallOption) (*PhotoDataRsp, error) {
	out := new(PhotoDataRsp)
	err := grpc.Invoke(ctx, "/mtproto.RPCNbfs/nbfs_uploadPhotoFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCNbfsClient) NbfsGetPhotoFileData(ctx context.Context, in *GetPhotoFileDataRequest, opts ...grpc.CallOption) (*PhotoDataRsp, error) {
	out := new(PhotoDataRsp)
	err := grpc.Invoke(ctx, "/mtproto.RPCNbfs/nbfs_getPhotoFileData", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RPCNbfs service

type RPCNbfsServer interface {
	NbfsUploadPhotoFile(context.Context, *UploadPhotoFileRequest) (*PhotoDataRsp, error)
	NbfsGetPhotoFileData(context.Context, *GetPhotoFileDataRequest) (*PhotoDataRsp, error)
}

func RegisterRPCNbfsServer(s *grpc.Server, srv RPCNbfsServer) {
	s.RegisterService(&_RPCNbfs_serviceDesc, srv)
}

func _RPCNbfs_NbfsUploadPhotoFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadPhotoFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCNbfsServer).NbfsUploadPhotoFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtproto.RPCNbfs/NbfsUploadPhotoFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCNbfsServer).NbfsUploadPhotoFile(ctx, req.(*UploadPhotoFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCNbfs_NbfsGetPhotoFileData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPhotoFileDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCNbfsServer).NbfsGetPhotoFileData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtproto.RPCNbfs/NbfsGetPhotoFileData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCNbfsServer).NbfsGetPhotoFileData(ctx, req.(*GetPhotoFileDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPCNbfs_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mtproto.RPCNbfs",
	HandlerType: (*RPCNbfsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "nbfs_uploadPhotoFile",
			Handler:    _RPCNbfs_NbfsUploadPhotoFile_Handler,
		},
		{
			MethodName: "nbfs_getPhotoFileData",
			Handler:    _RPCNbfs_NbfsGetPhotoFileData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nbfs_service.proto",
}

func init() { proto.RegisterFile("nbfs_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x4f, 0x4f, 0xb3, 0x40,
	0x10, 0xc6, 0x03, 0x7d, 0xf3, 0x52, 0x47, 0x4f, 0x6b, 0xab, 0xd8, 0x8b, 0x84, 0x44, 0xd3, 0xd3,
	0x9a, 0x54, 0x3f, 0x41, 0x35, 0x2a, 0x89, 0x69, 0x08, 0xc6, 0x0b, 0x17, 0xc2, 0x9f, 0xc1, 0x6e,
	0xb2, 0xb0, 0xc8, 0x2e, 0x1a, 0xf9, 0x4a, 0x7e, 0x49, 0xc3, 0x2a, 0x24, 0x18, 0xeb, 0x09, 0x66,
	0xe6, 0xd9, 0xdf, 0xcc, 0xf3, 0x00, 0x29, 0x93, 0x5c, 0x46, 0x12, 0xeb, 0x57, 0x96, 0x22, 0xad,
	0x6a, 0xa1, 0x04, 0xb1, 0x0a, 0xa5, 0x7f, 0x16, 0x33, 0x99, 0x6e, 0xb1, 0x88, 0xa9, 0xe2, 0x54,
	0xbe, 0x97, 0xe9, 0xd7, 0xd8, 0x0d, 0xe1, 0xe8, 0xa9, 0xe2, 0x22, 0xce, 0xfc, 0xad, 0x50, 0xe2,
	0x96, 0x71, 0x0c, 0xf0, 0xa5, 0x41, 0xa9, 0x88, 0x0d, 0x96, 0x78, 0x2b, 0xb1, 0xf6, 0x32, 0xdb,
	0x70, 0x8c, 0xe5, 0x24, 0xe8, 0x4b, 0x72, 0x0e, 0xff, 0x72, 0xc6, 0xd1, 0x36, 0x1d, 0x63, 0xb9,
	0xbf, 0x22, 0xf4, 0x7b, 0x03, 0xf5, 0xca, 0xaa, 0x51, 0x1a, 0xa1, 0xe7, 0xee, 0x15, 0x1c, 0xdf,
	0xa1, 0x1a, 0xc0, 0x37, 0xb1, 0x8a, 0x7b, 0xf8, 0x09, 0x4c, 0xab, 0xae, 0x1f, 0xb1, 0x81, 0xae,
	0x6b, 0x2f, 0x73, 0x43, 0x38, 0xd0, 0x4f, 0xb4, 0x5c, 0x56, 0x7f, 0x48, 0xc9, 0x05, 0xec, 0x49,
	0xd6, 0x62, 0xc4, 0x99, 0x54, 0xb6, 0xe9, 0x4c, 0x46, 0xd7, 0x68, 0xc8, 0x23, 0x6b, 0x31, 0x98,
	0x76, 0xa2, 0x07, 0x26, 0xd5, 0xea, 0xc3, 0x00, 0x2b, 0xf0, 0xaf, 0x37, 0x49, 0x2e, 0xc9, 0x06,
	0x66, 0x3a, 0xae, 0x66, 0x6c, 0x9f, 0x9c, 0x0e, 0x84, 0xdf, 0x83, 0x59, 0xcc, 0xc7, 0x2b, 0xfa,
	0x3b, 0x7d, 0x98, 0x6b, 0xde, 0xf3, 0x0f, 0xcb, 0xc4, 0x19, 0xf4, 0x3b, 0xd2, 0xd8, 0x41, 0x5c,
	0x9f, 0xc1, 0x61, 0x2a, 0x0a, 0x5a, 0x62, 0xd2, 0xf0, 0x98, 0x15, 0xb4, 0xd5, 0x9a, 0x35, 0x84,
	0x7e, 0xf7, 0xed, 0x4c, 0xdc, 0x9b, 0xbe, 0x91, 0xfc, 0xd7, 0xed, 0xcb, 0xcf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x1f, 0x5d, 0x7e, 0xdf, 0xfe, 0x01, 0x00, 0x00,
}
