// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zproto_sync.proto

package mtproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 同步类型
type SyncType int32

const (
	SyncType_SYNC_TYPE_UNKNOWN    SyncType = 0
	SyncType_SYNC_TYPE_USER       SyncType = 1
	SyncType_SYNC_TYPE_USER_NOTME SyncType = 2
	SyncType_SYNC_TYPE_USER_ME    SyncType = 3
)

var SyncType_name = map[int32]string{
	0: "SYNC_TYPE_UNKNOWN",
	1: "SYNC_TYPE_USER",
	2: "SYNC_TYPE_USER_NOTME",
	3: "SYNC_TYPE_USER_ME",
}
var SyncType_value = map[string]int32{
	"SYNC_TYPE_UNKNOWN":    0,
	"SYNC_TYPE_USER":       1,
	"SYNC_TYPE_USER_NOTME": 2,
	"SYNC_TYPE_USER_ME":    3,
}

func (x SyncType) String() string {
	return proto.EnumName(SyncType_name, int32(x))
}
func (SyncType) EnumDescriptor() ([]byte, []int) { return fileDescriptor10, []int{0} }

type VoidRsp struct {
}

func (m *VoidRsp) Reset()                    { *m = VoidRsp{} }
func (m *VoidRsp) String() string            { return proto.CompactTextString(m) }
func (*VoidRsp) ProtoMessage()               {}
func (*VoidRsp) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{0} }

// PushMessage state
type ClientUpdatesState struct {
	Pts      int32 `protobuf:"varint,1,opt,name=pts" json:"pts,omitempty"`
	PtsCount int32 `protobuf:"varint,2,opt,name=pts_count,json=ptsCount" json:"pts_count,omitempty"`
	Qts      int32 `protobuf:"varint,3,opt,name=qts" json:"qts,omitempty"`
	QtsCount int32 `protobuf:"varint,4,opt,name=qts_count,json=qtsCount" json:"qts_count,omitempty"`
	Seq      int32 `protobuf:"varint,5,opt,name=seq" json:"seq,omitempty"`
	SeqStart int32 `protobuf:"varint,6,opt,name=seq_start,json=seqStart" json:"seq_start,omitempty"`
	Date     int32 `protobuf:"varint,7,opt,name=date" json:"date,omitempty"`
}

func (m *ClientUpdatesState) Reset()                    { *m = ClientUpdatesState{} }
func (m *ClientUpdatesState) String() string            { return proto.CompactTextString(m) }
func (*ClientUpdatesState) ProtoMessage()               {}
func (*ClientUpdatesState) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{1} }

func (m *ClientUpdatesState) GetPts() int32 {
	if m != nil {
		return m.Pts
	}
	return 0
}

func (m *ClientUpdatesState) GetPtsCount() int32 {
	if m != nil {
		return m.PtsCount
	}
	return 0
}

func (m *ClientUpdatesState) GetQts() int32 {
	if m != nil {
		return m.Qts
	}
	return 0
}

func (m *ClientUpdatesState) GetQtsCount() int32 {
	if m != nil {
		return m.QtsCount
	}
	return 0
}

func (m *ClientUpdatesState) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *ClientUpdatesState) GetSeqStart() int32 {
	if m != nil {
		return m.SeqStart
	}
	return 0
}

func (m *ClientUpdatesState) GetDate() int32 {
	if m != nil {
		return m.Date
	}
	return 0
}

// /////////////////////////////////////////////////////////////////////
// SERVER_AUTH_REQ
type ConnectToSessionServerReq struct {
}

func (m *ConnectToSessionServerReq) Reset()                    { *m = ConnectToSessionServerReq{} }
func (m *ConnectToSessionServerReq) String() string            { return proto.CompactTextString(m) }
func (*ConnectToSessionServerReq) ProtoMessage()               {}
func (*ConnectToSessionServerReq) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{2} }

type SessionServerConnectedRsp struct {
	ServerId   int32  `protobuf:"varint,1,opt,name=server_id,json=serverId" json:"server_id,omitempty"`
	ServerName string `protobuf:"bytes,2,opt,name=server_name,json=serverName" json:"server_name,omitempty"`
}

func (m *SessionServerConnectedRsp) Reset()                    { *m = SessionServerConnectedRsp{} }
func (m *SessionServerConnectedRsp) String() string            { return proto.CompactTextString(m) }
func (*SessionServerConnectedRsp) ProtoMessage()               {}
func (*SessionServerConnectedRsp) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{3} }

func (m *SessionServerConnectedRsp) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *SessionServerConnectedRsp) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

// PushUpdatesData --> VoidRsp
type PushUpdatesData struct {
	AuthKeyId   int64               `protobuf:"varint,1,opt,name=auth_key_id,json=authKeyId" json:"auth_key_id,omitempty"`
	SessionId   int64               `protobuf:"varint,2,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	State       *ClientUpdatesState `protobuf:"bytes,3,opt,name=state" json:"state,omitempty"`
	UpdatesData []byte              `protobuf:"bytes,5,opt,name=updates_data,json=updatesData,proto3" json:"updates_data,omitempty"`
}

func (m *PushUpdatesData) Reset()                    { *m = PushUpdatesData{} }
func (m *PushUpdatesData) String() string            { return proto.CompactTextString(m) }
func (*PushUpdatesData) ProtoMessage()               {}
func (*PushUpdatesData) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{4} }

func (m *PushUpdatesData) GetAuthKeyId() int64 {
	if m != nil {
		return m.AuthKeyId
	}
	return 0
}

func (m *PushUpdatesData) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *PushUpdatesData) GetState() *ClientUpdatesState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *PushUpdatesData) GetUpdatesData() []byte {
	if m != nil {
		return m.UpdatesData
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////
// RPC
type UpdatesRequest struct {
	PushType   SyncType `protobuf:"varint,1,opt,name=push_type,json=pushType,enum=mtproto.SyncType" json:"push_type,omitempty"`
	AuthKeyId  int64    `protobuf:"varint,2,opt,name=auth_key_id,json=authKeyId" json:"auth_key_id,omitempty"`
	SessionId  int64    `protobuf:"varint,3,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	PushUserId int32    `protobuf:"varint,4,opt,name=push_user_id,json=pushUserId" json:"push_user_id,omitempty"`
	Updates    *Updates `protobuf:"bytes,5,opt,name=updates" json:"updates,omitempty"`
}

func (m *UpdatesRequest) Reset()                    { *m = UpdatesRequest{} }
func (m *UpdatesRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdatesRequest) ProtoMessage()               {}
func (*UpdatesRequest) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{5} }

func (m *UpdatesRequest) GetPushType() SyncType {
	if m != nil {
		return m.PushType
	}
	return SyncType_SYNC_TYPE_UNKNOWN
}

func (m *UpdatesRequest) GetAuthKeyId() int64 {
	if m != nil {
		return m.AuthKeyId
	}
	return 0
}

func (m *UpdatesRequest) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *UpdatesRequest) GetPushUserId() int32 {
	if m != nil {
		return m.PushUserId
	}
	return 0
}

func (m *UpdatesRequest) GetUpdates() *Updates {
	if m != nil {
		return m.Updates
	}
	return nil
}

type UpdatesListRequest struct {
	UpdatesList []*UpdatesRequest `protobuf:"bytes,1,rep,name=updates_list,json=updatesList" json:"updates_list,omitempty"`
}

func (m *UpdatesListRequest) Reset()                    { *m = UpdatesListRequest{} }
func (m *UpdatesListRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdatesListRequest) ProtoMessage()               {}
func (*UpdatesListRequest) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{6} }

func (m *UpdatesListRequest) GetUpdatesList() []*UpdatesRequest {
	if m != nil {
		return m.UpdatesList
	}
	return nil
}

func init() {
	proto.RegisterType((*VoidRsp)(nil), "mtproto.VoidRsp")
	proto.RegisterType((*ClientUpdatesState)(nil), "mtproto.ClientUpdatesState")
	proto.RegisterType((*ConnectToSessionServerReq)(nil), "mtproto.ConnectToSessionServerReq")
	proto.RegisterType((*SessionServerConnectedRsp)(nil), "mtproto.SessionServerConnectedRsp")
	proto.RegisterType((*PushUpdatesData)(nil), "mtproto.PushUpdatesData")
	proto.RegisterType((*UpdatesRequest)(nil), "mtproto.UpdatesRequest")
	proto.RegisterType((*UpdatesListRequest)(nil), "mtproto.UpdatesListRequest")
	proto.RegisterEnum("mtproto.SyncType", SyncType_name, SyncType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RPCSync service

type RPCSyncClient interface {
	SyncUpdatesData(ctx context.Context, in *UpdatesRequest, opts ...grpc.CallOption) (*ClientUpdatesState, error)
	PushUpdatesData(ctx context.Context, in *UpdatesRequest, opts ...grpc.CallOption) (*VoidRsp, error)
}

type rPCSyncClient struct {
	cc *grpc.ClientConn
}

func NewRPCSyncClient(cc *grpc.ClientConn) RPCSyncClient {
	return &rPCSyncClient{cc}
}

func (c *rPCSyncClient) SyncUpdatesData(ctx context.Context, in *UpdatesRequest, opts ...grpc.CallOption) (*ClientUpdatesState, error) {
	out := new(ClientUpdatesState)
	err := grpc.Invoke(ctx, "/mtproto.RPCSync/SyncUpdatesData", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCSyncClient) PushUpdatesData(ctx context.Context, in *UpdatesRequest, opts ...grpc.CallOption) (*VoidRsp, error) {
	out := new(VoidRsp)
	err := grpc.Invoke(ctx, "/mtproto.RPCSync/PushUpdatesData", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RPCSync service

type RPCSyncServer interface {
	SyncUpdatesData(context.Context, *UpdatesRequest) (*ClientUpdatesState, error)
	PushUpdatesData(context.Context, *UpdatesRequest) (*VoidRsp, error)
}

func RegisterRPCSyncServer(s *grpc.Server, srv RPCSyncServer) {
	s.RegisterService(&_RPCSync_serviceDesc, srv)
}

func _RPCSync_SyncUpdatesData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCSyncServer).SyncUpdatesData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtproto.RPCSync/SyncUpdatesData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCSyncServer).SyncUpdatesData(ctx, req.(*UpdatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCSync_PushUpdatesData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCSyncServer).PushUpdatesData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtproto.RPCSync/PushUpdatesData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCSyncServer).PushUpdatesData(ctx, req.(*UpdatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPCSync_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mtproto.RPCSync",
	HandlerType: (*RPCSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncUpdatesData",
			Handler:    _RPCSync_SyncUpdatesData_Handler,
		},
		{
			MethodName: "PushUpdatesData",
			Handler:    _RPCSync_PushUpdatesData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zproto_sync.proto",
}

func init() { proto.RegisterFile("zproto_sync.proto", fileDescriptor10) }

var fileDescriptor10 = []byte{
	// 579 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xfd, 0x1c, 0xb7, 0x4d, 0x32, 0xae, 0x5a, 0x77, 0xbf, 0x22, 0xdc, 0x56, 0x40, 0xb1, 0x84,
	0x54, 0xf5, 0xc2, 0x12, 0xe1, 0x0e, 0x71, 0xd5, 0x10, 0x41, 0x54, 0xea, 0x5a, 0x76, 0x02, 0x0a,
	0x37, 0xd6, 0xd6, 0x5e, 0x14, 0x8b, 0xf8, 0x2f, 0xb3, 0x46, 0x32, 0x4f, 0xc1, 0x53, 0xf0, 0x06,
	0x3c, 0x06, 0xef, 0x84, 0x76, 0xd7, 0xf9, 0x69, 0xa2, 0xf6, 0xca, 0xe3, 0x33, 0x27, 0xb3, 0xe7,
	0x9c, 0x9d, 0x18, 0x8e, 0x7e, 0x16, 0xf3, 0x9c, 0xe7, 0x21, 0xd6, 0x59, 0xe4, 0xc8, 0x92, 0xb4,
	0x53, 0x2e, 0x8b, 0xd3, 0x63, 0x8c, 0xa6, 0x2c, 0xa5, 0x0e, 0x9f, 0x39, 0xab, 0xb6, 0xdd, 0x85,
	0xf6, 0xe7, 0x3c, 0x89, 0x7d, 0x2c, 0xec, 0x3f, 0x1a, 0x90, 0xfe, 0x2c, 0x61, 0x19, 0x1f, 0x17,
	0x31, 0xe5, 0x0c, 0x03, 0x4e, 0x39, 0x23, 0x26, 0xe8, 0x05, 0x47, 0x4b, 0x3b, 0xd7, 0x2e, 0x76,
	0x7d, 0x51, 0x92, 0x33, 0xe8, 0x16, 0x1c, 0xc3, 0x28, 0xaf, 0x32, 0x6e, 0xb5, 0x24, 0xde, 0x29,
	0x38, 0xf6, 0xc5, 0xbb, 0xa0, 0x97, 0x1c, 0x2d, 0x5d, 0xd1, 0x4b, 0x45, 0x2f, 0x97, 0xf4, 0x1d,
	0x45, 0x2f, 0xd7, 0xe8, 0xc8, 0x4a, 0x6b, 0x57, 0xd1, 0x91, 0x95, 0x82, 0x8e, 0xac, 0x0c, 0x91,
	0xd3, 0x39, 0xb7, 0xf6, 0x14, 0x1d, 0x59, 0x19, 0x88, 0x77, 0x42, 0x60, 0x47, 0x48, 0xb3, 0xda,
	0x12, 0x97, 0xb5, 0x7d, 0x06, 0x27, 0xfd, 0x3c, 0xcb, 0x58, 0xc4, 0x47, 0x79, 0xc0, 0x10, 0x93,
	0x3c, 0x0b, 0xd8, 0xfc, 0x07, 0x9b, 0xfb, 0xac, 0xb4, 0x27, 0x70, 0x72, 0x0f, 0x6b, 0x98, 0x4c,
	0x38, 0x56, 0x47, 0x09, 0x34, 0x4c, 0xe2, 0xc6, 0x60, 0x47, 0x01, 0xc3, 0x98, 0xbc, 0x00, 0xa3,
	0x69, 0x66, 0x34, 0x65, 0xd2, 0x67, 0xd7, 0x07, 0x05, 0xb9, 0x34, 0x65, 0xf6, 0x6f, 0x0d, 0x0e,
	0xbd, 0x0a, 0xa7, 0x4d, 0x5a, 0xef, 0x29, 0xa7, 0xe4, 0x39, 0x18, 0xb4, 0xe2, 0xd3, 0xf0, 0x3b,
	0xab, 0x17, 0x33, 0x75, 0xbf, 0x2b, 0xa0, 0x6b, 0x56, 0x0f, 0x63, 0xf2, 0x0c, 0x00, 0x95, 0x1c,
	0xd1, 0x6e, 0xa9, 0x76, 0x83, 0x0c, 0x63, 0xf2, 0x1a, 0x76, 0x51, 0x84, 0x2e, 0xe3, 0x33, 0x7a,
	0x67, 0x4e, 0x73, 0x79, 0xce, 0xf6, 0xbd, 0xf8, 0x8a, 0x49, 0x5e, 0xc2, 0x7e, 0xa5, 0xe0, 0x30,
	0xa6, 0x9c, 0xca, 0x24, 0xf7, 0x7d, 0xa3, 0x5a, 0x89, 0xb2, 0xff, 0x6a, 0x70, 0xd0, 0xfc, 0xd4,
	0x67, 0x65, 0xc5, 0x90, 0x13, 0x07, 0xba, 0x45, 0x85, 0xd3, 0x90, 0xd7, 0x05, 0x93, 0x2a, 0x0f,
	0x7a, 0x47, 0xcb, 0xc3, 0x82, 0x3a, 0x8b, 0x46, 0x75, 0xc1, 0xfc, 0x8e, 0xe0, 0x88, 0x6a, 0xd3,
	0x57, 0xeb, 0x71, 0x5f, 0xfa, 0xa6, 0xaf, 0x73, 0xd8, 0x97, 0xc7, 0x55, 0xa8, 0xb2, 0x56, 0x5b,
	0x00, 0x02, 0x1b, 0xa3, 0x4c, 0xfb, 0x12, 0xda, 0x8d, 0x64, 0xe9, 0xc0, 0xe8, 0x99, 0x4b, 0x39,
	0x0b, 0xe9, 0x0b, 0x82, 0xed, 0x01, 0x69, 0xb0, 0x4f, 0x09, 0xf2, 0x85, 0xa5, 0xb7, 0xab, 0x20,
	0x66, 0x09, 0x72, 0x4b, 0x3b, 0xd7, 0x2f, 0x8c, 0xde, 0xd3, 0xad, 0x31, 0x8a, 0xbe, 0x4c, 0x48,
	0x8c, 0xb8, 0xfc, 0x06, 0x9d, 0x85, 0x69, 0xf2, 0x04, 0x8e, 0x82, 0x89, 0xdb, 0x0f, 0x47, 0x13,
	0x6f, 0x10, 0x8e, 0xdd, 0x6b, 0xf7, 0xf6, 0x8b, 0x6b, 0xfe, 0x47, 0x08, 0x1c, 0xac, 0xc1, 0xc1,
	0xc0, 0x37, 0x35, 0x62, 0xc1, 0xf1, 0x7d, 0x2c, 0x74, 0x6f, 0x47, 0x37, 0x03, 0xb3, 0xb5, 0x31,
	0x44, 0x74, 0x6e, 0x06, 0xa6, 0xde, 0xfb, 0xa5, 0x41, 0xdb, 0xf7, 0xfa, 0xe2, 0x2c, 0xf2, 0x01,
	0x0e, 0xc5, 0x73, 0x7d, 0x7b, 0x1e, 0x12, 0x7b, 0xfa, 0xd8, 0x22, 0x90, 0x77, 0xdb, 0x6b, 0xf8,
	0xe0, 0xa0, 0x55, 0xaa, 0xcd, 0xbf, 0xfe, 0xea, 0x15, 0xfc, 0x1f, 0xe5, 0xa9, 0x93, 0xb1, 0xbb,
	0x6a, 0x46, 0x93, 0xd4, 0x51, 0x5f, 0x90, 0x2b, 0xf8, 0xea, 0x89, 0xa7, 0x50, 0xf8, 0xb1, 0xe5,
	0x69, 0x77, 0x7b, 0x12, 0x7e, 0xf3, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x4b, 0x28, 0x9b, 0x75, 0x62,
	0x04, 0x00, 0x00,
}
