// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zproto_auth_key.proto

package mtproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type AuthKeyMetadata struct {
	Nonce       []byte `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce []byte `protobuf:"bytes,2,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	NewNonce    []byte `protobuf:"bytes,3,opt,name=new_nonce,json=newNonce,proto3" json:"new_nonce,omitempty"`
	A           []byte `protobuf:"bytes,4,opt,name=a,proto3" json:"a,omitempty"`
	P           []byte `protobuf:"bytes,5,opt,name=p,proto3" json:"p,omitempty"`
	AuthKeyId   int64  `protobuf:"varint,6,opt,name=auth_key_id,json=authKeyId" json:"auth_key_id,omitempty"`
	AuthKey     []byte `protobuf:"bytes,7,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
}

func (m *AuthKeyMetadata) Reset()                    { *m = AuthKeyMetadata{} }
func (m *AuthKeyMetadata) String() string            { return proto.CompactTextString(m) }
func (*AuthKeyMetadata) ProtoMessage()               {}
func (*AuthKeyMetadata) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{0} }

func (m *AuthKeyMetadata) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *AuthKeyMetadata) GetServerNonce() []byte {
	if m != nil {
		return m.ServerNonce
	}
	return nil
}

func (m *AuthKeyMetadata) GetNewNonce() []byte {
	if m != nil {
		return m.NewNonce
	}
	return nil
}

func (m *AuthKeyMetadata) GetA() []byte {
	if m != nil {
		return m.A
	}
	return nil
}

func (m *AuthKeyMetadata) GetP() []byte {
	if m != nil {
		return m.P
	}
	return nil
}

func (m *AuthKeyMetadata) GetAuthKeyId() int64 {
	if m != nil {
		return m.AuthKeyId
	}
	return 0
}

func (m *AuthKeyMetadata) GetAuthKey() []byte {
	if m != nil {
		return m.AuthKey
	}
	return nil
}

type AuthKeyRequest struct {
	AuthKeyId int64 `protobuf:"varint,1,opt,name=auth_key_id,json=authKeyId" json:"auth_key_id,omitempty"`
}

func (m *AuthKeyRequest) Reset()                    { *m = AuthKeyRequest{} }
func (m *AuthKeyRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthKeyRequest) ProtoMessage()               {}
func (*AuthKeyRequest) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{1} }

func (m *AuthKeyRequest) GetAuthKeyId() int64 {
	if m != nil {
		return m.AuthKeyId
	}
	return 0
}

type AuthKeyData struct {
	Result    int32  `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	AuthKeyId int64  `protobuf:"varint,2,opt,name=auth_key_id,json=authKeyId" json:"auth_key_id,omitempty"`
	AuthKey   []byte `protobuf:"bytes,3,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
}

func (m *AuthKeyData) Reset()                    { *m = AuthKeyData{} }
func (m *AuthKeyData) String() string            { return proto.CompactTextString(m) }
func (*AuthKeyData) ProtoMessage()               {}
func (*AuthKeyData) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{2} }

func (m *AuthKeyData) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *AuthKeyData) GetAuthKeyId() int64 {
	if m != nil {
		return m.AuthKeyId
	}
	return 0
}

func (m *AuthKeyData) GetAuthKey() []byte {
	if m != nil {
		return m.AuthKey
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthKeyMetadata)(nil), "mtproto.AuthKeyMetadata")
	proto.RegisterType((*AuthKeyRequest)(nil), "mtproto.AuthKeyRequest")
	proto.RegisterType((*AuthKeyData)(nil), "mtproto.AuthKeyData")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ZRPCAuthKey service

type ZRPCAuthKeyClient interface {
	QueryAuthKey(ctx context.Context, in *AuthKeyRequest, opts ...grpc.CallOption) (*AuthKeyData, error)
}

type zRPCAuthKeyClient struct {
	cc *grpc.ClientConn
}

func NewZRPCAuthKeyClient(cc *grpc.ClientConn) ZRPCAuthKeyClient {
	return &zRPCAuthKeyClient{cc}
}

func (c *zRPCAuthKeyClient) QueryAuthKey(ctx context.Context, in *AuthKeyRequest, opts ...grpc.CallOption) (*AuthKeyData, error) {
	out := new(AuthKeyData)
	err := grpc.Invoke(ctx, "/mtproto.ZRPCAuthKey/QueryAuthKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ZRPCAuthKey service

type ZRPCAuthKeyServer interface {
	QueryAuthKey(context.Context, *AuthKeyRequest) (*AuthKeyData, error)
}

func RegisterZRPCAuthKeyServer(s *grpc.Server, srv ZRPCAuthKeyServer) {
	s.RegisterService(&_ZRPCAuthKey_serviceDesc, srv)
}

func _ZRPCAuthKey_QueryAuthKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZRPCAuthKeyServer).QueryAuthKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtproto.ZRPCAuthKey/QueryAuthKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZRPCAuthKeyServer).QueryAuthKey(ctx, req.(*AuthKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ZRPCAuthKey_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mtproto.ZRPCAuthKey",
	HandlerType: (*ZRPCAuthKeyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryAuthKey",
			Handler:    _ZRPCAuthKey_QueryAuthKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zproto_auth_key.proto",
}

func init() { proto.RegisterFile("zproto_auth_key.proto", fileDescriptor10) }

var fileDescriptor10 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4b, 0x4f, 0x83, 0x40,
	0x10, 0xc7, 0xb3, 0xad, 0x7d, 0x0d, 0x44, 0xe3, 0x5a, 0x15, 0x35, 0x31, 0x95, 0x53, 0x0f, 0x86,
	0x18, 0x3d, 0x7b, 0xb0, 0x7a, 0xd0, 0xf8, 0x08, 0xee, 0xb1, 0x17, 0xdc, 0xc2, 0x24, 0x6d, 0x2c,
	0x0f, 0x61, 0xd7, 0x06, 0x3f, 0x9c, 0x9f, 0xcd, 0xec, 0x83, 0x43, 0x39, 0x78, 0x82, 0xff, 0xfe,
	0x66, 0x86, 0x1f, 0x3b, 0x70, 0xf8, 0x53, 0x94, 0xb9, 0xc8, 0x23, 0x2e, 0xc5, 0x32, 0xfa, 0xc4,
	0x3a, 0xd0, 0x91, 0x0e, 0x52, 0xa1, 0x5f, 0xfc, 0x5f, 0x02, 0x7b, 0x77, 0x52, 0x2c, 0x9f, 0xb1,
	0x7e, 0x45, 0xc1, 0x13, 0x2e, 0x38, 0x1d, 0x43, 0x2f, 0xcb, 0xb3, 0x18, 0x3d, 0x32, 0x21, 0x53,
	0x97, 0x99, 0x40, 0x2f, 0xc0, 0xad, 0xb0, 0xfc, 0xc6, 0x32, 0x32, 0xb0, 0xa3, 0xa1, 0x63, 0xce,
	0xde, 0x74, 0xc9, 0x19, 0x8c, 0x32, 0xdc, 0x58, 0xde, 0xd5, 0x7c, 0x98, 0xe1, 0xc6, 0x40, 0x17,
	0x08, 0xf7, 0x76, 0xf4, 0x21, 0xe1, 0x2a, 0x15, 0x5e, 0xcf, 0xa4, 0x82, 0x9e, 0x83, 0xd3, 0x08,
	0x46, 0xab, 0xc4, 0xeb, 0x4f, 0xc8, 0xb4, 0xcb, 0x46, 0xdc, 0x78, 0x3d, 0x25, 0xf4, 0x04, 0x86,
	0x0d, 0xf7, 0x06, 0xba, 0x69, 0x60, 0xa1, 0x7f, 0x05, 0xbb, 0xd6, 0x9f, 0xe1, 0x97, 0xc4, 0x4a,
	0xb4, 0x87, 0x91, 0xd6, 0x30, 0xff, 0x03, 0x1c, 0xdb, 0xf1, 0xa0, 0xfe, 0xf6, 0x08, 0xfa, 0x25,
	0x56, 0x72, 0x2d, 0x74, 0x65, 0x8f, 0xd9, 0xd4, 0x1e, 0xd3, 0xf9, 0xcf, 0xa9, 0xbb, 0xe5, 0x74,
	0xfd, 0x02, 0xce, 0x9c, 0x85, 0xf7, 0xf6, 0x2b, 0xf4, 0x16, 0xdc, 0x77, 0x89, 0x65, 0xdd, 0xe4,
	0xe3, 0xc0, 0xde, 0x7e, 0xb0, 0x6d, 0x7e, 0x3a, 0x6e, 0x03, 0x25, 0x38, 0xbb, 0x84, 0x83, 0x38,
	0x4f, 0x83, 0x0c, 0x17, 0x72, 0xcd, 0x57, 0x69, 0x60, 0x36, 0x3a, 0xdb, 0x9f, 0x87, 0xea, 0xc9,
	0x8a, 0x58, 0x2d, 0x4e, 0x55, 0x3e, 0x76, 0x42, 0xb2, 0xe8, 0x6b, 0x7a, 0xf3, 0x17, 0x00, 0x00,
	0xff, 0xff, 0x5b, 0x66, 0xcb, 0x33, 0xf9, 0x01, 0x00, 0x00,
}
